### ISSUE TITLE
Heatmaps do not work

### ISSUE THREAD

**Issue by amraladdin** [architecture-building-systems/CityEnergyAnalyst#1357] opened 2018-05-19 10:31 UTC
I tried generating the heatmaps for scenario RES_Low Density. After successfully running the demand, I tried to generate the heatmaps for the area, using the Total_demand.csv file. I chose the following outputs:
- QCf_MWhyr
- QHf_MWhyr
- QEf_MWhyr

The tool generated the following error:

```
Executing: HeatmapsTool C:\reference-case\reference-case-WTP\RES_low_density Total_demand.csv QCf_MWhyr;QEf_MWhyr;QHf_MWhyr
Start Time: Sat May 19 12:27:38 2018
Running script HeatmapsTool...
Executing: C:\ProgramData\Miniconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli heatmaps --analysis-fields QCf_MWhyr, QEf_MWhyr, QHf_MWhyr --file-to-analyze C:\reference-case\reference-case-WTP\RES_low_density\outputs\data\demand\Total_demand.csv --scenario C:\reference-case\reference-case-WTP\RES_low_density
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 32, in main
    script_module = importlib.import_module(module_path)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\heatmaps.py", line 11, in <module>
    from cea.interfaces.arcgis.modules import arcpy
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\arcgis\modules.py", line 34, in <module>
    import arcpy
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\__init__.py", line 22, in <module>
    from arcpy.geoprocessing import gp
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\geoprocessing\__init__.py", line 14, in <module>
    from _base import *
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\geoprocessing\_base.py", line 14, in <module>
    import arcgisscripting
ImportError: No module named arcgisscripting


Traceback (most recent call last):
  File "<string>", line 285, in execute
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 77, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 164, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (HeatmapsTool).
Failed at Sat May 19 12:27:38 2018 (Elapsed Time: 0.29 seconds)

```

Does this mean we will not use the Heatmap feature during the workshop? Then I would rather we take the feature away from the toolbox.

Apologize for assigning you directly @JIMENOFONSECA @gabriel-happle

**Comment by JIMENOFONSECA** [comment] 2018-05-19 12:31
It seems you are missing background geoprocessing from arcgis. Dis you install it?

On 19 May 2018, 18:31 +0800, Amr Elesawy <notifications@github.com>, wrote:

I tried generating the heatmaps for scenario RES_Low Density. After successfully running the demand, I tried to generate the heatmaps for the area, using the Total_demand.csv file. I chose the following outputs:

  *   QCf_MWhyr
  *   QHf_MWhyr
-QEf_MWhyr

The tool generated the following error:

Executing: HeatmapsTool C:\reference-case\reference-case-WTP\RES_low_density Total_demand.csv QCf_MWhyr;QEf_MWhyr;QHf_MWhyr
Start Time: Sat May 19 12:27:38 2018
Running script HeatmapsTool...
Executing: C:\ProgramData\Miniconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli heatmaps --analysis-fields QCf_MWhyr, QEf_MWhyr, QHf_MWhyr --file-to-analyze C:\reference-case\reference-case-WTP\RES_low_density\outputs\data\demand\Total_demand.csv --scenario C:\reference-case\reference-case-WTP\RES_low_density
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 32, in main
    script_module = importlib.import_module(module_path)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\heatmaps.py", line 11, in <module>
    from cea.interfaces.arcgis.modules import arcpy
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\arcgis\modules.py", line 34, in <module>
    import arcpy
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\__init__.py", line 22, in <module>
    from arcpy.geoprocessing import gp
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\geoprocessing\__init__.py", line 14, in <module>
    from _base import *
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\geoprocessing\_base.py", line 14, in <module>
    import arcgisscripting
ImportError: No module named arcgisscripting


Traceback (most recent call last):
  File "<string>", line 285, in execute
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 77, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 164, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (HeatmapsTool).
Failed at Sat May 19 12:27:38 2018 (Elapsed Time: 0.29 seconds)



Does this mean we will not use the Heatmap feature during the workshop? Then I would rather we take the feature away from the toolbox.

Apologize for assigning you directly @JIMENOFONSECA<https://github.com/JIMENOFONSECA> @gabriel-happle<https://github.com/gabriel-happle>

**Comment by gabriel-happle** [comment] 2018-05-21 01:53
@amraladdin check the executive slack channel for the installation file of background geoprocessing.
Zhongming posted it there on May 16th.

**Comment by gabriel-happle** [comment] 2018-05-21 01:54
possible duplicate of #1291

**Comment by amraladdin** [comment] 2018-05-22 11:49
I'm working with ArcGIS 10.4. When I installed Geoprocessing, it featured the following error:
![image](https://user-images.githubusercontent.com/16256867/40360579-e5e06336-5dc6-11e8-82ee-ab27af484d83.png)

**Comment by JIMENOFONSECA** [comment] 2018-05-22 12:36
computer says you need 10.5, just agree with it :-)

On 22 May 2018, 19:49 +0800, Amr Elesawy <notifications@github.com>, wrote:

I'm working with ArcGIS 10.4. When I installed Geoprocessing, it featured the following error:
[image]<https://user-images.githubusercontent.com/16256867/40360579-e5e06336-5dc6-11e8-82ee-ab27af484d83.png>

**Comment by amraladdin** [comment] 2018-05-22 12:59
:D So, I did that, but still the Heatmaps didn't work. Still got the same error:

```
Executing: HeatmapsTool C:\reference-case\reference-case-WTP\RES_low_density Total_demand.csv Ef_MWhyr;Qcs_MWhyr
Start Time: Tue May 22 14:58:49 2018
Running script HeatmapsTool...
Executing: C:\ProgramData\Miniconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli heatmaps --analysis-fields Ef_MWhyr, Qcs_MWhyr --file-to-analyze C:\reference-case\reference-case-WTP\RES_low_density\outputs\data\demand\Total_demand.csv --scenario C:\reference-case\reference-case-WTP\RES_low_density
Traceback (most recent call last):
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 174, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 79, in <module>
    main(cea.config.Configuration())
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 32, in main
    script_module = importlib.import_module(module_path)
  File "C:\ProgramData\Miniconda2\envs\cea\lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\plots\heatmaps.py", line 11, in <module>
    from cea.interfaces.arcgis.modules import arcpy
  File "c:\users\aelesawy\documents\github\cityenergyanalyst\cea\interfaces\arcgis\modules.py", line 34, in <module>
    import arcpy
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\__init__.py", line 22, in <module>
    from arcpy.geoprocessing import gp
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\geoprocessing\__init__.py", line 14, in <module>
    from _base import *
  File "C:\Program Files (x86)\ArcGIS\Desktop10.4\arcpy\arcpy\geoprocessing\_base.py", line 14, in <module>
    import arcgisscripting
ImportError: No module named arcgisscripting


Traceback (most recent call last):
  File "<string>", line 285, in execute
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 77, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\aelesawy\AppData\Roaming\ESRI\Desktop10.4\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 164, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (HeatmapsTool).
Failed at Tue May 22 14:58:51 2018 (Elapsed Time: 1.56 seconds)
```

**Comment by martin-mosteiro** [comment] 2018-05-23 11:33
@amraladdin Are you sure you installed ArcGIS 10.5 *and* BackgroundGP? For example, I have ArcGIS 10.5.1 with BackgroundGP for 10.5.1 and the heatmaps tool doesn't work for me (see #1355). We should make sure it works in the computer lab, if it does, we can use the tool tomorrow, if not, we'll have to skip it.

**Comment by amraladdin** [comment] 2018-05-23 13:53
No, I didn't install ArcGIS 10.5, I have 10.4 on my PC. Sure... Let's check the tool in the Lab, however, we cannot install it ourselves, we need to talk to the IT guys tomorrow morning.

**Comment by daren-thomas** [comment] 2018-05-28 09:55
@amraladdin did the tool work in the lab?

**Comment by amraladdin** [comment] 2018-05-28 12:58
We did not have time to install the tool in the HIL Lab, so we couldn't test it.

**Comment by daren-thomas** [comment] 2018-05-28 15:03
@amraladdin I don't understand this answer. it _was_ installed, wasn't it? did you just not run the heatmaps, is that what you're saying?

**Comment by daren-thomas** [comment] 2018-05-29 07:14
@amraladdin you sure? i mean, did you check? because, i'm pretty sure we did install, back, when we originally specified how to install arcgis...

**Closed** 2018-05-29 09:01 UTC
Labels: Priority 1
