### ISSUE TITLE
Zone.shp input error to create new scenario

### ISSUE THREAD

**Issue by LeoTom95** [architecture-building-systems/CityEnergyAnalyst#2753] opened 2020-05-29 20:57 UTC
Good morning,
I'm Leonardo Tomasetto, I've been working with CEA for a few months to check the consumption of a neighborhood for a university thesis study. In recent days I had to update the software to version 3.3.0 and I encountered the following problem:
when I try to create a new scenario with the zone.shp file that I created in Qgis and I have used up to now the input page does not load the file and does not allow me to continue.
If instead I create a scenario with the CEA tool this works perfectly and keeps me going.
I need to import my shape file in order to continue my analysis, are there solutions?
Thanks for the attention.

**Comment by reyery** [comment] 2020-05-30 01:03
Hey @LeoTom95, if you don't mind, could you upload the shapefile that you used and a screenshot of what the CEA is showing, so that we can try to reproduce the issue on our end to solve it. Thanks.

**Comment by LeoTom95** [comment] 2020-05-30 08:32
[zone.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/4705336/zone.zip)
<img width="1440" alt="Schermata 2020-05-30 alle 10 24 38" src="https://user-images.githubusercontent.com/66142001/83323564-07d23c00-a260-11ea-92d5-ab4d3112f14c.png">

Hi @reyery , I'll send you the requested file.
If you see the screenshot, the problem occurs when I click create, it doesn't give me an error code, the program simply doesn't load. I have tried with other .shp, even those created by the CEA tool, but it doesn't work anyway.
Thanks

**Comment by reyery** [comment] 2020-06-02 01:56
After testing, it seems to be a problem with the GUI not accepting the form when user is using "import" method caused by a field in the "generate" method throwing an error. A fix has been created and would be added to the new release coming in the next few days.

**Comment by daren-thomas** [comment] 2020-06-09 07:51
the PR is in the GUI, @daren-thomas will test this. 

https://github.com/architecture-building-systems/CityEnergyAnalyst-GUI/pull/28

**Comment by daren-thomas** [comment] 2020-06-09 08:59
fixed in GUI - will be deployed with next release end of this week.

**Closed by daren-thomas** 2020-06-09 08:59 UTC
Labels: bug

**Comment by Mar-Ges** [comment] 2020-12-16 08:54
Hi all, 

I want to create my scenario by importing a shapefile. The occurring problem is close to the one described by LeoTom.

Since I got the first errors I want to use a shapefile generated by CEA (from another scenario; [zone.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/5701379/zone.zip) ). I can create a new scenario by using the import function, but when I open the input editor there is an unknown error. 
Simulating the energy demands of a scenario created by the CEA tools is working. I'm using version 3.11.0.

Thanks in advance

**Comment by Mar-Ges** [comment] 2020-12-16 10:34
(I installed version 3.15.0 -> same error)
