### ISSUE TITLE
database crashing after clicking components-conversion-chiller_configuration

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2956] opened 2021-04-19 08:47 UTC
**Describe the bug**
Database editor crashes after switching specific tabs

**To Reproduce**
1. Go to database editor of any scenario
2. Click on components - conversion
3. Switch to components - distribution (example)
4.  Switch back to components - conversion
5. Click on any different tab inside components - conversion (e.g. boiler, chiller)
6. See error (TypeError: Cannot read property 'columns' of undefined)

**Expected behaviour**
switch tabs normally between tabs in database editos

![image](https://user-images.githubusercontent.com/50981039/115206938-b5c32f00-a12d-11eb-9fc8-e6714fb66f65.png)

 - Version of CEA 3.22

**Comment by shanshanhsieh** [comment] 2022-03-01 12:47
this problem still exists in v3.27

**Comment by shanshanhsieh** [comment] 2022-04-26 20:58
i think the problem is the `Chiller_configuration` tab

**Comment by shanshanhsieh** [comment] 2022-04-26 21:09
this is a duplicate of #3044

**Closed by shanshanhsieh** 2022-04-26 21:09 UTC
Labels: bug, Should have, Interface, known issue
