### ISSUE TITLE
CEA installation guide for Mac

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#2197] opened 2019-07-23 08:40 UTC
I have managed to install CEA on a Mac computer. Hooray! The steps to follow need to be added to the website.

**Comment by daren-thomas** [comment] 2019-08-16 09:55
@JIMENOFONSECA I am having a hard time compiling the binaries for DAYSIM on Mac. I managed to compile them with one strategy, but `radiation-daysim` doesn't work with those. I'm not sure exactly what the issue is.

DAYSIM does not seem to be properly supported on Mac OS.

Would it be acceptable to leave the radiation-daysim script as unsupported by a osx installation? The user could still use the docker version to create the radiation files - or a windows installation. The rest should work just fine.

**Comment by JIMENOFONSECA** [comment] 2019-08-19 03:02
Hi Daren,

I see…well maybe we can make it available and when the users start to bring the issue up, we revisit it?

I guess this will buy us time but not solve the problem?



On 16 Aug 2019, 5:55 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> I am having a hard time compiling the binaries for DAYSIM on Mac. I managed to compile them with one strategy, but radiation-daysim doesn't work with those. I'm not sure exactly what the issue is.

DAYSIM does not seem to be properly supported on Mac OS.

Would it be acceptable to leave the radiation-daysim script as unsupported by a osx installation? The user could still use the docker version to create the radiation files - or a windows installation. The rest should work just fine.

**Comment by daren-thomas** [comment] 2019-08-26 08:44
@JIMENOFONSECA what is the reason for closing the issue? It's unclear to me if this is a "won't-have" or "closed-because-implemented" - the PR is still open. Do we scrap that or merge it in it's current state? Or update it to reflect the fact that not everything will work?

**Comment by JIMENOFONSECA** [comment] 2019-08-26 11:36
ups... I thought the PR was implemented. my bad.


Jimeno

________________________________

**Closed** 2019-09-18 13:59 UTC
Labels: documentation
