### ISSUE TITLE
Plots tool requires values to be selected that are not needed for the selected plots

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1413] opened 2018-05-29 11:01 UTC
I get the following error when running the plots tool:
![screen shot 2018-05-29 at 12 58 03](https://user-images.githubusercontent.com/18548065/40654988-25259952-6340-11e8-8768-fdc8fef3afda.png)
i.e., need to specify a value in the "Advanced" settings in order to run the plots tool even if I am not attempting to produce the plots affected by this value. This is a bug in itself, but on top of that, I'm unable to write anything in the field in question (no numbers or text appear in the box and nothing happens when typing in the box), so I am unable to run the plots tool at all.

**Comment by martin-mosteiro** [comment] 2018-05-29 11:03
Update: after trying for the fourth time to type in a number, it worked. So I was able to produce the plots I wanted to produce. Nonetheless, the first part of the issue still holds.

**Comment by martin-mosteiro** [comment] 2018-05-29 11:04
Same issue as found in the box "Path to scenarios to run comparison graphs for": these values should only be required when attempting to produce the plots that require them.
![screen shot 2018-05-29 at 13 04 06](https://user-images.githubusercontent.com/18548065/40655196-e3242f22-6340-11e8-91d6-c5c35ee4dc67.png)

**Comment by daren-thomas** [comment] 2018-05-29 11:27
duplicate of #1386, fixed in PR #1414

**Closed** 2018-06-04 12:59 UTC
Labels: bug
