### ISSUE TITLE
Namin.csv is still there, move it to schemas

### ISSUE THREAD

**Issue by JIMENOFONSECA** [architecture-building-systems/CityEnergyAnalyst#2718] opened 2020-04-30 09:47 UTC
**Describe the bug**
So it seems the schemas are not connected to the plots, this was supposed to be changed by now? @daren-thomas mind taking a look?

**To Reproduce**

**Expected behaviour**

**Screenshots**

**Hardware (please complete the following information):**
 - OS and version: [e.g. iOS 10.7 or Windows 10]
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by daren-thomas** [comment] 2020-04-30 09:53
@JIMENOFONSECA this is a duplicate of #2680. It has been moved down in importance relative to other issues.

The main problem is that `naming.csv` refers to variables that are not necessarily output-file columns - some of them are aggregations made ad-hoc in the plots themselves.

**Closed by daren-thomas** 2020-04-30 09:53 UTC
Labels: Must have, bug

**Comment by JIMENOFONSECA** [comment] 2020-05-01 01:42
Once again. That is not an intended behavior. If it is, the plot is just wrong and should be removed. We spent a lot of time making possible that the output variables go directly into the plots without any ‘aggregation’.

So the schemas should replace naming.csv as of now without any need of postprocessing the outputs.
On 30 Apr 2020, 17:54 +0800, Daren Thomas <notifications@github.com>, wrote:

Closed #2718<https://github.com/architecture-building-systems/CityEnergyAnalyst/issues/2718>.
