### ISSUE TITLE
BUG: zug case demand breaks down because of MASSIVE data center internal gains

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1256] opened 2018-04-20 10:27 UTC
Since the my last testing of the Zug case in #1189 the demand is not running anymore.
A workaround is to reduce the power of the data center internal loads in `Bau 16` to a lower value.
@martin-mosteiro we have to look at this.

**Comment by martin-mosteiro** [comment] 2018-04-23 01:39
@gabriel-happle That is what was happening to me too with building `B302007073` and the same "solution" I found...

**Comment by martin-mosteiro** [comment] 2018-04-23 06:09
@gabriel-happle Found the issue. The internal loads for `Bau 16` include a demand of 500 W/m2 for the data center. That would be the demand if the building was 100% SERVERROOM, but only 4% of it is. So actually the electricity demand for data the entire building should be 0.04*500 W/m2 = 20 W/m2.

However, if the building *was* 100% SERVERROOM we would still get the same problem you found... so the problem is solved for `Bau 16` but there might be cases in which we would get the same error for a different building...

**Comment by gabriel-happle** [comment] 2018-04-23 06:29
@martin-mosteiro so the input files are wrong because of previous issues with the data helper? Do I understand correctly?
It means all of the internal loads of mixed use buildings in Zug are actually off?

**Comment by martin-mosteiro** [comment] 2018-04-23 06:44
Yes... But even if you correct that the internal gains are too high for the RC-model to handle them, it seems.

**Comment by martin-mosteiro** [comment] 2018-04-23 09:11
The value of 500 W/m2 for server rooms does **not** come from SIA 2024.

The SIA value for appliances in a server room is 50 - 150 W/m2, but the standard does specify that these values are **not** for data centers ("The demands for rooms with particularly energy intensive process facilities such as operation rooms, process heat, compressed air, clean rooms or data centers need to be determined on a project-specific basis", p. 9)

**Comment by martin-mosteiro** [comment] 2018-05-31 12:11
I did. And in any case the cooling system's capacity was greater than the internal gains in all my tests, but the thermal mass was still getting overheated.

As discussed on Pycharm, I agree the issue is that data center cooling demand should be treated as process cooling, not space cooling. This solves the issue of overheating based on my tests on the HSQ case study and it is actually basically the solution I pursued for my presentation last week.

**Comment by daren-thomas** [comment] 2018-06-05 13:58
@martin-mosteiro what is the status of this issue?

**Comment by martin-mosteiro** [comment] 2018-06-05 14:30
@JIMENOFONSECA is working on a PR to solve this issue among others.

**Comment by daren-thomas** [comment] 2018-06-11 09:30
@JIMENOFONSECA what is the status of this issue? is it resolved?

**Comment by JIMENOFONSECA** [comment] 2018-06-11 09:32
yes, let’s close it

On 11 Jun 2018, 5:31 PM +0800, Daren Thomas <notifications@github.com>, wrote:

@JIMENOFONSECA<https://github.com/JIMENOFONSECA> what is the status of this issue? is it resolved?

**Closed** 2018-06-11 12:03 UTC
Labels: Priority 1, bug, help wanted
