### ISSUE TITLE
Selecting buildings ('Draw') on a map generates error

### ISSUE THREAD

**Issue by arnoschlueter** [architecture-building-systems/CityEnergyAnalyst#2738] opened 2020-05-18 09:14 UTC
Selecting buildings ('Draw') on a map generates error:
' UnicodeDecodeError: 'utf8' codec can't decode byte 0xe4 in position 13: invalid continuation byte'

> Tried multiple times for a map in Zurich, in vicinity of the railroad tracks at main station (Jimeno once mentioned railroad buildings / tracks) are an issue.

**Comment by daren-thomas** [comment] 2020-05-19 07:09
@reyery can you please try to reproduce this bug?

**Comment by daren-thomas** [comment] 2020-05-19 07:22
Adding to the issue: The search bar does not react to "Zürich", but will accept "Zurich".

**Comment by daren-thomas** [comment] 2020-05-19 07:27
@arnoschlueter we were not able to re-produce your error. Could you please post a screenshot of your selection before clicking "Create"?

We've tried two examples including the train tracks - one near Central and the other encompassing Europaallee, Lagerstrasse and the HB itself - it seems to be working for us?

**Comment by arnoschlueter** [comment] 2020-05-19 08:29
apologies, me neither at this point. Maybe restart of tool / windows helped.

Best, Arno
On 19 May 2020, 09:28 +0200, Daren Thomas <notifications@github.com>, wrote:

@arnoschlueter<https://github.com/arnoschlueter> we were not able to re-produce your error. Could you please post a screenshot of your selection before clicking "Create"?

We've tried two examples including the train tracks - one near Central and the other encompassing Europaallee, Lagerstrasse and the HB itself - it seems to be working for us?

**Comment by daren-thomas** [comment] 2020-05-20 07:16
closing as not reproducible.

**Closed by daren-thomas** 2020-05-20 07:16 UTC
Labels: bug
