### ISSUE TITLE
Bug testing optimization: "Missing network edge list"

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1301] opened 2018-05-14 06:56 UTC
```Executing: OptimizationTool C:\Users\Gabriel\Documents\GitHub\cea-reference-case\reference-case-WTP\03_MIX_medium_density\baseline 2 20 2 1 604800 true false
Start Time: Mon May 14 14:50:02 2018
Running script OptimizationTool...
Executing: C:\Users\Gabriel\Anaconda2\envs\cea\python.exe -u -m cea.interfaces.cli.cli optimization --scenario C:\Users\Gabriel\Documents\GitHub\cea-reference-case\reference-case-WTP\03_MIX_medium_density\baseline --fcheckpoint 1 --ngen 2 --halloffame 20 --iscooling true --initialind 2 --maxtime 604800 --isheating false
Missing network edge list. Consider running thermal network script first

Traceback (most recent call last):
  File "C:\Users\Gabriel\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 68, in execute
    run_cli(self.cea_tool, **kwargs)
  File "C:\Users\Gabriel\AppData\Roaming\ESRI\Desktop10.5\ArcToolbox\My Toolboxes\cea\interfaces\arcgis\arcgishelper.py", line 155, in run_cli
    raise Exception('Tool did not run successfully')
Exception: Tool did not run successfully

Failed to execute (OptimizationTool).
Failed at Mon May 14 14:50:11 2018 (Elapsed Time: 8.41 seconds)```

**Comment by gabriel-happle** [comment] 2018-05-14 08:46
@daren-thomas this issue seems to have many aspects.
one of them seems to be that the ArcGIS interface of `optimization` and `thermal networks` does not modify/change and save the `config` file in the right way.
I.e., changes in the ArcGIS window are only partly transferred to the config file

**Comment by daren-thomas** [comment] 2018-05-23 10:10
@gabriel-happle I think I see the problem now. Or at least, suspect what is happening: I assume, the "changes in the config file" you're talking about are the parameters to running the script. The `main` function of the script accepts a `config` parameter which contains the configuration. If, however, you decide to create your own instance of `cea.config.Configuration` further down in the script, these parameters will not be picked up. This is by design! Also, don't do that! Pass down the `config` object from the main function as intended.

**Comment by daren-thomas** [comment] 2018-05-23 10:20
Here are problematic instances of creating a `cea.config.Configuration` instances done by searching all the files in the project:

- cea/technologies/thermal_network/thermal_network_matrix.py : 573 `weather_file = cea.config.Configuration().weather`
- cea/globalvar.py : 19 : `self.config = cea.config.Configuration()self.config = cea.config.Configuration()`
  - is this still being used? if so, then that is most likely the culprit!
- none other found

**Comment by gabriel-happle** [comment] 2018-05-23 10:42
@daren-thomas in this case, I'm just the first tester who found this problem and therefore created the issue.
I think @BhargavaKrishnaSreepathi 's help is needed here to fix this.

**Comment by daren-thomas** [comment] 2018-05-29 11:20
@gabriel-happle @BhargavaKrishnaSreepathi what is the current status of this issue?

**Comment by daren-thomas** [comment] 2018-06-11 09:30
@gabriel-happle @BhargavaKrishnaSreepathi what is the current status of this issue?

**Comment by BhargavaKrishnaSreepathi** [comment] 2018-06-11 09:36
I think this is no longer an issue. I think this got fixed in one of PRs in the past two weeks

**Closed by BhargavaKrishnaSreepathi** 2018-06-11 09:36 UTC
Labels: Interface, Priority 1, bug
