### ISSUE TITLE
Remove global variables file and split it into multiple settings files

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#753] opened 2017-07-21 06:01 UTC
Global variables file is to be phased out. Transfer all the variables to the corresponding settings files in the respective folders

**Comment by BhargavaKrishnaSreepathi** [comment] 2017-08-24 09:43
@daren-thomas: To resolve this issue, we can still save the relevant values from the `globalvar.py` into `settings.py` file which is local to sub folder like say optimization right? So remove the variables corresponding to optimization from `globalvar.py` and paste them into `optimization_settings.py` inside `cea\optimization` folder. Does this sound ok?

**Comment by daren-thomas** [comment] 2017-08-31 14:59
you can. but what you really want to do is move them to the configuration file. see some of the pull requests i've posted that work in this direction. moving the variables to an `optimization_settings.py` file could be a valid first step, though. like a stepping stone...

**Comment by JIMENOFONSECA** [comment] 2018-10-03 09:36
@daren-thomas do you think we can close this issue now?

**Comment by JIMENOFONSECA** [comment] 2018-11-08 07:05
@daren-thomas ??

**Comment by daren-thomas** [comment] 2018-11-08 15:32
@JIMENOFONSECA no. I don't think so. The issue is still open!

PR #1675 addresses a lot of the low hanging fruit, but there are still some parts of the optimization code and the neural network code that rely on this module.

**Comment by JIMENOFONSECA** [comment] 2019-03-20 01:52
@daren-thomas @BhargavaKrishnaSreepathi do you think we can close this issue now? if not, which is the plan of action?

**Comment by daren-thomas** [comment] 2019-04-04 08:46
@JIMENOFONSECA It is still being used extensively in the metamodel/nn_generator scripts - what is the status of those? do they work? should they be moved to legacy if they don't?

Other places to fix:

- `cea.demand.occupancy_model.main`: uses `gv.date_start` (this can be fixed, right, @gabriel-happle?)
- `cea.optimization.optimization_main.main`: used in multiple places...
- `cea.demand.calibration.subset_calibrator.subset_calibrator.ss_calibrator` - @JIMENOFONSECA is this yours?
- `cea.supply.supply_system_simulation.main` - basically, because optimization still uses `gv`
- some other places that we can probably remove...
- conclusion: we're close. one last push?

**Comment by gabriel-happle** [comment] 2019-04-04 09:10
@daren-thomas I will take a look at the first point and fix it.

**Comment by daren-thomas** [comment] 2019-05-14 12:41
So there are still some places we need to look at:
- `cea/analysis/mcda.py`  (@JIMENOFONSECA, I think this is your script?)
- `cea.analysis.uncertainty.Individual_Evaluation` (@shanshanhsieh, this should be an easy fix, I think the variables used are mainly in the config file - except "num_tot_buildings"?)
- `cea/demand/subset_calibrator/`  - (this folder still has some usages in it - I'm hesitant to change anything in here since I think most stuff will change...)
- `cea/optimization/optimization_main.py:63` - (@shanshanhsieh, the optimization code uses a `gv.num_tot_buildings` - as well as some other small things. could you please take a look at that?)

**Comment by daren-thomas** [comment] 2019-05-16 09:35
we can delete the `cea/demand/subset_calibrator/` folder

**Comment by JIMENOFONSECA** [comment] 2019-05-21 03:06
@daren-thomas we take over this, so you can focus on the plots and the dashboard

**Comment by JIMENOFONSECA** [comment] 2019-07-25 09:31
#2120 took down gv from the optimization. the subset calibration should be taken out

**Comment by daren-thomas** [comment] 2019-07-25 09:36
Daren is going to review it, @JIMENOFONSECA and @shanshanhsieh think it's done.

**Comment by daren-thomas** [comment] 2019-08-14 13:30
STATUS UPDATE:

- class `Thermal_Network` takes a `gv` parameter in  its constructor
  - how to test if removing that will create a problem?
  - btw: the class name should be `ThermalNetwork` and why is it defined in `thermal_network_costs`?
  - @shanshanhsieh can you check this out quickly?
- the following packages are old and will never ever work again without being updated:
  - `cea.demand.calibration.subset_calibrator`
  - `cea.demand.metamodel.nn_generator`
  - these need to be updated to work again or removed from the codebase
  - @JIMENOFONSECA you probably know more about this than anyone else, right?
- I'm creating a PR with the obvious fixes, the above remain as they might alter/change/remove functionality.

**Closed** 2019-09-18 13:58 UTC
Labels: Must have
