### ISSUE TITLE
Solar radiation normalization fails

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#2675] opened 2020-03-28 16:25 UTC
**Describe the bug**
Solar radiation normalization fails

**To Reproduce**
Demand forecasting -> Building solar radiation

Dashboard -> Add plot

Solar potentials -> Solar radiation

Next -> Normalization

Something went wrong!

**Expected behaviour**
Normalized solar radiation graph

**Screenshots**
![1](https://user-images.githubusercontent.com/29708612/77827935-ab508480-7129-11ea-85d9-dc16ca030f32.jpg)
![2](https://user-images.githubusercontent.com/29708612/77827938-aee40b80-7129-11ea-9944-12415ec6fcd1.jpg)
![3](https://user-images.githubusercontent.com/29708612/77827939-b1466580-7129-11ea-9d16-405624741681.jpg)
![4](https://user-images.githubusercontent.com/29708612/77827940-b3a8bf80-7129-11ea-91b3-36458f5fb851.jpg)

**Hardware (please complete the following information):**
 - OS and version: Windows 8.1
 - CEA 3.0.2

**Comment by reyery** [comment] 2020-04-03 11:51
@kerembeygo could you try opening CEA Console and run `cea dashboard` so we could see the output log of CEA. After seeing "**start socketio.run**" in the console, launch the Dasboard GUI. Try to reproduce the bug and see if there are any error messages in the console.

**Comment by kerembeygo** [comment] 2020-04-04 10:10
![1](https://user-images.githubusercontent.com/29708612/78424347-90c06300-7675-11ea-9762-ee39034d1533.jpg)

**Comment by kerembeygo** [comment] 2020-04-04 10:10
![2](https://user-images.githubusercontent.com/29708612/78424358-a170d900-7675-11ea-9b21-cfaa3488f251.jpg)

**Comment by kerembeygo** [comment] 2020-04-04 10:10
![3](https://user-images.githubusercontent.com/29708612/78424374-b3eb1280-7675-11ea-826c-873b566581ac.jpg)

**Comment by kerembeygo** [comment] 2020-04-04 10:11
![4](https://user-images.githubusercontent.com/29708612/78424380-c36a5b80-7675-11ea-9f9d-bee39bb660a4.jpg)

**Comment by kerembeygo** [comment] 2020-04-04 10:12
![5](https://user-images.githubusercontent.com/29708612/78424403-ef85dc80-7675-11ea-820e-29c3eec3a6dd.jpg)

**Comment by kerembeygo** [comment] 2020-04-04 10:13
![6](https://user-images.githubusercontent.com/29708612/78424431-1ba15d80-7676-11ea-8f28-54ea92cb5b2b.jpg)

**Comment by kerembeygo** [comment] 2020-04-04 10:18
Last plot is yearly. Time span on x-axis?

**Comment by reyery** [comment] 2020-04-07 13:34
Hmm.. seems that the plots work now.
The last plot is showing the data resampled(sum) to years. The x-axis should just indicate the year i.e. **2009** not a range, will fix that.

**Comment by reyery** [comment] 2020-04-22 05:13
Layout of x-axis for time frames fixed in #2691. We could not fix solar radiation normalization since we could not recreate the issue on our end. If it fails again, you could reopen/create an issue.

**Closed by reyery** 2020-04-22 05:13 UTC
Labels: bug
