### ISSUE TITLE
CityEnergyAnalyst v2.9.0 run time error

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#1694] opened 2018-11-18 12:46 UTC
![cea error 1](https://user-images.githubusercontent.com/29708612/48672702-4c005e80-eb4a-11e8-95fd-0f619f4c2c9e.jpg)
![cea error 2](https://user-images.githubusercontent.com/29708612/48672703-4c98f500-eb4a-11e8-9914-78b532849522.jpg)
![cea error 3](https://user-images.githubusercontent.com/29708612/48672704-4c98f500-eb4a-11e8-885c-c735d9133ea1.jpg)
![folder connections toolboxes](https://user-images.githubusercontent.com/29708612/48672705-4c98f500-eb4a-11e8-9222-9a5995ec793a.jpg)
![radiation 1](https://user-images.githubusercontent.com/29708612/48672706-4d318b80-eb4a-11e8-87ff-308e64819fda.jpg)
![run demand](https://user-images.githubusercontent.com/29708612/48672707-4d318b80-eb4a-11e8-8ea0-33ed6668afeb.jpg)

I downloaded CEA 2.9 and ran Solar Radiation Tool, Demand Tool. I received following messages. Does CEA 2.9 automatically clean previous versions?

**Comment by daren-thomas** [comment] 2018-11-21 14:36
@kerembeygo you're on the right version. it seems you are trying to run the demand script for a scenario that doesn't exist?

**Comment by kerembeygo** [comment] 2018-11-22 18:13
Get started with CEA -> Download a test case study -> reference-case-WTP.zip 
My folder connections are as below
![fc](https://user-images.githubusercontent.com/29708612/48917597-a0804280-ee98-11e8-9875-61c040f8a7ca.jpg)
I ran each scenario for WTP. 
![run](https://user-images.githubusercontent.com/29708612/48917630-dc1b0c80-ee98-11e8-8bec-0a4673639bcc.jpg)
![1](https://user-images.githubusercontent.com/29708612/48917668-15537c80-ee99-11e8-9159-ba45965b0813.jpg)
![2](https://user-images.githubusercontent.com/29708612/48917699-361bd200-ee99-11e8-9f77-85d586a76ed2.jpg)
![3](https://user-images.githubusercontent.com/29708612/48917715-56e42780-ee99-11e8-80d6-e7d9db224de3.jpg)
![4](https://user-images.githubusercontent.com/29708612/48917743-7a0ed700-ee99-11e8-8056-a4df88ac4348.jpg)
![5](https://user-images.githubusercontent.com/29708612/48917791-b5110a80-ee99-11e8-94fc-5940d2652d00.jpg)
![6](https://user-images.githubusercontent.com/29708612/48917844-ebe72080-ee99-11e8-8a08-a045912f84ac.jpg)
Same error message for each scenario. I hope I'm doing everything right. I don't have any other test case. I can try if you have.

**Comment by daren-thomas** [comment] 2018-11-23 10:30
@kerembeygo do you have DAYSIM installed? You can download and install it here: https://daysim.ning.com/page/download

**Comment by kerembeygo** [comment] 2018-11-23 12:00
I had it in Urban Modeling Interface. I installed 4.0 release.
![1](https://user-images.githubusercontent.com/29708612/48942216-94938f80-ef2f-11e8-8e1e-7bcb66e2ff6e.jpg)
Fiona Warning! for GDAL and PROJ data files
![2](https://user-images.githubusercontent.com/29708612/48942275-d91f2b00-ef2f-11e8-90a5-dcb9ceda8f7a.jpg)
![3](https://user-images.githubusercontent.com/29708612/48942285-eb00ce00-ef2f-11e8-94df-21f3e1662eef.jpg)
Demand Forecasting
![4](https://user-images.githubusercontent.com/29708612/48942326-0e2b7d80-ef30-11e8-89fb-b403b6d8ec81.jpg)
![5](https://user-images.githubusercontent.com/29708612/48942360-33b88700-ef30-11e8-9ae6-61972a2b94e3.jpg)
Failed to execute DemandTool

**Comment by daren-thomas** [comment] 2018-11-26 13:41
@gabriel-happle do you have any idea what is wrong here? (`KeyError: Qcre_Wm2` seems to be the actual error for the demand script.

**Comment by gabriel-happle** [comment] 2018-11-27 03:41
Hi @daren-thomas and @kerembeygo, I can reproduce this error with the current master.
Trying to figure out what is causing it.

**Comment by gabriel-happle** [comment] 2018-11-27 03:57
Hi @daren-thomas and @kerembeygo. The problem is caused by outdated case study files.
The solution is a simple as running the `data-helper` script again.
In the meantime I will update the case study files.

**Comment by gabriel-happle** [comment] 2018-11-27 06:19
@daren-thomas PR #1699 should solve this. Please take a look. Thanks.

**Comment by gabriel-happle** [comment] 2018-11-27 06:21
@kerembeygo please close this issue, if your problem is resolved. Thanks.

**Comment by kerembeygo** [comment] 2018-11-27 19:51
Demand run for reference-case-open results a different error. "KeyError: u'B01'
![reference-case-open demand tool](https://user-images.githubusercontent.com/29708612/49107394-a9a55100-f296-11e8-896b-1c4de17cd414.jpg)
 "

**Comment by gabriel-happle** [comment] 2018-11-28 07:55
Hi @kerembeygo, it's hard to know what is causing your errors. I just ran the reference-case-open successfully yesterday.
Could you document the steps of your simulation and maybe share your files?
The error says that there is no building 'B01' in your file `inputs\building-properties\supply_systems.dbf`.
Maybe you can open the file in ArcGIS and check the contents of the attribute table to see if there is something wrong.

**Comment by kerembeygo** [comment] 2018-11-28 12:44
Hi @gabriel-happle , I downloaded reference cases from your website yesterday. 
Demand Run
![demand run](https://user-images.githubusercontent.com/29708612/49150914-55927f00-f31f-11e8-8137-03a526dda700.jpg)
![demand1](https://user-images.githubusercontent.com/29708612/49150953-6cd16c80-f31f-11e8-927b-042a47e26066.jpg)
![demand2](https://user-images.githubusercontent.com/29708612/49150967-7b1f8880-f31f-11e8-98fa-ec29326a5263.jpg)
![demand3](https://user-images.githubusercontent.com/29708612/49150985-85418700-f31f-11e8-9b49-f27c81d2c9dd.jpg)
inputs\building-properties\supply_systems
![building properties](https://user-images.githubusercontent.com/29708612/49151139-26304200-f320-11e8-8ed6-fcafbcd813b8.jpg)
Supply systems
![supply systems dbf](https://user-images.githubusercontent.com/29708612/49151210-5c6dc180-f320-11e8-8c75-ad3385437b3b.jpg)
[reference-case-open.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2624418/reference-case-open.zip)

**Comment by kerembeygo** [comment] 2018-11-28 13:17
Demand run WTP
![demand wtp run](https://user-images.githubusercontent.com/29708612/49154189-dd30bb80-f328-11e8-8fee-a6838af63574.jpg)
![demand wtp 1](https://user-images.githubusercontent.com/29708612/49154207-e28e0600-f328-11e8-9291-95f4d007e044.jpg)
![demand wtp 2](https://user-images.githubusercontent.com/29708612/49154217-eb7ed780-f328-11e8-9447-6bd2598bc82d.jpg)
WTP is not updated yet I assume.

**Comment by gabriel-happle** [comment] 2018-11-29 02:39
@kerembeygo 
1) the `reference-case-open` is supposed to be in region `CH`, the building properties were generated using the `CH` databases. If you execute the demand now for `SIN` some links in the databases will not work. Hence this Error. If you want to run this case study for `SIN`, you can simply execute the `data-helper` with region `SIN` first to create new building models.
Be aware, that you also have to calculate the radiation again, since the `reference-case-open` contains already calculated radiation results from the `Zug` weather file.

2) as said above, you can just run the `data-helper` script before running the demand. Make sure to use region `SIN`. There is no need to download the test cases again.

In general, you should always follow the following procedure:
1. Run `data-helper`
2. Run `radiation`
3. Run `demand`
It is your responsibility that the simulation parameters make sense. I.e., don't run radiation and demand with different weather files, etc.

**Comment by kerembeygo** [comment] 2018-11-29 17:09
Hi @gabriel-happle 
Thank you for your brief explanation, solar radiation and demand tools ran successfully.
I don't know whether the manuals are up to date with the latest enhancements of CEA but I want to try other features and that will take a couple of days I guess.

**Closed** 2018-11-29 17:15 UTC
Labels: Must have, User Support, bug

**Comment by gabriel-happle** [comment] 2019-04-01 05:51
Dear @kerembeygo,

In order for us to better understand the needs of our users and steer the development of the tool in the future we would like to understand why and how you are using the CityEnergyAnalyst.

Please help us by answering 10 short questions in the [CEA user survey](https://forms.gle/6nR8V5JEDM593g5eA).
The feedback we receive will determine the focus of the upcoming development efforts.

Kind regards,
The CEA development team
