### ISSUE TITLE
Daysim Error: fatal - file chunk_0.dc does not contain any uncommented lines

### ISSUE THREAD

**Issue by fracityanalist** [architecture-building-systems/CityEnergyAnalyst#3578] opened 2024-05-11 09:57 UTC
I'm getting this error when I run the solar radiation in Windows 11 Pro with 11th Gen Intel(R) Core(TM) i5-1135G7 @ 2.40GHz   2.42 GHz processor. I already checked the Raypath variable and it's ok. Also, I can't find any temporary file with the name tmprf2gie5h, do you have any suggestions? 

b'IN CASE YOU ARE USING DAYSIM UNDER WINDOWS, THE "RAPYPATH" VARIALBE MIGHT NOT HAVE BEEN SET CORRECTLY. TO TEST THIS, OPEN A DOS PROMPT AND TYPE \'set\'. AMONG THE VARIALBLES DISPLAYED SHOULD BE \'Raypath c:\\Daysim\\lib\'.\r\nPLEASE REFER TO THE DAYSIM TUTORIAL FOR MORE INFORMATION...fatal - file C:\\Users\\franc\\AppData\\Local\\Temp\\tmprf2gie5h\\cea_radiation\\projects\\chunk_0\\chunk_0.dc does not contain any uncommented lines\r\n'

**Comment by reyery** [comment] 2024-05-14 14:27
Hi @fracityanalist, would you be able to share with us the scenario that you are running this for?
Based on the error, it is a Daysim error which could be caused my multiple factors and it is hard to reproduce it on our end without additional information. Thanks!

**Comment by reyery** [comment] 2024-05-28 11:43
Closing this issue for now since there hasn't been any response.
@fracityanalist let us know again if you need help with the issue.

**Closed by reyery** 2024-05-28 11:43 UTC
Labels: bug
