### ISSUE TITLE
Dashboard: multiple ambiguities with network calculation interface

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#2025] opened 2019-05-30 05:57 UTC
![image](https://user-images.githubusercontent.com/17002288/58611747-c45a9000-82e2-11e9-8484-c87ba89eded1.png)

**Comment by gabriel-happle** [comment] 2019-05-30 06:00
When opening the network interface, I noticed various small things that are unclear.
- network-name parameter is not clearly described
- representative-week option appears twice
- tool is for "branched" networks, diameter iteration mentions "looped" networks as well
- heating system should mention "DH" instead of "DC" (typo)

**Comment by daren-thomas** [comment] 2019-05-30 07:58
@gabriel-happle some of these might be linked also to #1925 - I think we're moving towards each script having it's own list of parameters. the `representative-week` option could be from that: maybe a whole section was imported in the `scripts.yml` and also separately referenced.

I also think we should go over the descriptive text for all parameters for all tools. A lot of them need need some editing.

**Comment by gabriel-happle** [comment] 2019-06-13 10:10
check `default.config` and `scripts.yml`

**Comment by daren-thomas** [comment] 2019-07-11 09:49
@shanshanhsieh check this quickly in the current interface to see if it is still an issue. the problem is probably in the `scripts.yml` file.

**Comment by shanshanhsieh** [comment] 2019-07-25 01:34
hey @daren-thomas , thanks for starting to clean up the config for this part!
i also removed some redundant network parameter and tested it

however, here i encounter a problem regarding the input-files requested in `scripts.yml`
i have to remove the first file to make the script run
![image](https://user-images.githubusercontent.com/16998305/61839187-3ef8f380-aebf-11e9-9a42-10bc2594afdf.png)

please advise what is the next step here. thanks!

**Comment by daren-thomas** [comment] 2019-07-25 09:54
OK, let's talk on monday

**Comment by reyery** [comment] 2019-08-08 09:21
@shanshanhsieh @daren-thomas so what is the status of this?

**Comment by JIMENOFONSECA** [comment] 2019-09-20 03:37
@daren-thomas @shanshanhsieh status please!

**Comment by shanshanhsieh** [comment] 2019-10-21 06:39
Just checked Thermal Network I & II on the dashboard with CEA version 2.23.
The interface is clean now thanks to the refactoring that was done by @daren-thomas in issue #2255

**Closed by shanshanhsieh** 2019-10-21 06:39 UTC
Labels: Interface, Must have, enhancement
