### ISSUE TITLE
CEA 2.7 run time error

### ISSUE THREAD

**Issue by kerembeygo** [architecture-building-systems/CityEnergyAnalyst#1412] opened 2018-05-28 16:56 UTC
![demand simulation 1](https://user-images.githubusercontent.com/29708612/40623628-686b09f8-6297-11e8-8e82-0b2c49f9a5f8.jpg)
![demand simulation 2](https://user-images.githubusercontent.com/29708612/40623629-68963830-6297-11e8-8d30-084fd846af4b.jpg)
![heatmaps](https://user-images.githubusercontent.com/29708612/40623631-68bf36a4-6297-11e8-9523-46d6f6e1bf7c.jpg)
![lca1](https://user-images.githubusercontent.com/29708612/40623632-68f63186-6297-11e8-8726-a3488ff54976.jpg)
![lca2](https://user-images.githubusercontent.com/29708612/40623633-692224bc-6297-11e8-9521-30163bbba2ee.jpg)
![retrofit potential 1](https://user-images.githubusercontent.com/29708612/40623634-69549410-6297-11e8-8318-41bed9d33e14.jpg)

![solar insolation](https://user-images.githubusercontent.com/29708612/40623673-95c4211e-6297-11e8-9e61-1b284afb0133.jpg)
![urban solar radiation 1](https://user-images.githubusercontent.com/29708612/40623675-967c497e-6297-11e8-9e49-dbb25ecf3f72.jpg)
![urban solar radiation 2](https://user-images.githubusercontent.com/29708612/40623677-973376a8-6297-11e8-9a7e-67a74f5fde59.jpg)
![urban solar radiation 3](https://user-images.githubusercontent.com/29708612/40623678-97e8b3a6-6297-11e8-8774-a522aaac8bdb.jpg)
![urban solar radiation 4](https://user-images.githubusercontent.com/29708612/40623680-98a39874-6297-11e8-9e95-54ed17f3393f.jpg)
![demand simulation 1](https://user-images.githubusercontent.com/29708612/40623664-934b89cc-6297-11e8-9715-ef838f7c7eff.jpg)
![demand simulation 2](https://user-images.githubusercontent.com/29708612/40623665-93a4264a-6297-11e8-924f-3c0222b35241.jpg)
![heatmaps](https://user-images.githubusercontent.com/29708612/40623667-93c9b7b6-6297-11e8-9e2f-f009bf1ed41c.jpg)
![lca1](https://user-images.githubusercontent.com/29708612/40623668-93f1bb4e-6297-11e8-9118-0d8b62ff1a21.jpg)
![lca2](https://user-images.githubusercontent.com/29708612/40623669-9422921e-6297-11e8-83d0-2ba6aeace389.jpg)
![retrofit potential 1](https://user-images.githubusercontent.com/29708612/40623670-94854c88-6297-11e8-9dbf-10238a6a56f8.jpg)
![retrofit potential 2](https://user-images.githubusercontent.com/29708612/40623672-9515cc0e-6297-11e8-8bdd-11dacd8b2731.jpg)
![Uploading Solar Insolation.jpg…]()
![Uploading Urban Solar Radiation 1.jpg…]()
![Uploading Urban Solar Radiation 2.jpg…]()
![Uploading Urban Solar Radiation 3.jpg…]()
![Uploading Urban Solar Radiation 4.jpg…]()

**Comment by JIMENOFONSECA** [comment] 2018-05-30 13:44
@kerembeygo Hi thanks, for putting an issue up. In order for us to help, please describe exactly what you were intending to do and a guide on how to replicate the error. @martin-mosteiro this apparently touches the sensitivity demand tool, so I add you to the conversation in case you have already some insights.

**Comment by martin-mosteiro** [comment] 2018-05-31 12:20
@kerembeygo Thanks for notifying us about the issue. Looks like there are quite a few different scripts being called up here and a few different issues popping up. I'll get to these one by one below.

**Comment by martin-mosteiro** [comment] 2018-05-31 12:21
These issues all point out to the shapefile for the zone of study being missing. Perhaps you did not select the scenario before running the respective tools?
![40623629-68963830-6297-11e8-8d30-084fd846af4b](https://user-images.githubusercontent.com/18548065/40781866-cfd1a42e-64dd-11e8-806f-7afb0b38e75e.jpg)
![40623665-93a4264a-6297-11e8-924f-3c0222b35241](https://user-images.githubusercontent.com/18548065/40781868-cff7abba-64dd-11e8-9b36-d2be7e9c18da.jpg)
![40623672-9515cc0e-6297-11e8-8bdd-11dacd8b2731](https://user-images.githubusercontent.com/18548065/40781869-d0130b26-64dd-11e8-8bc1-4b7a6c503066.jpg)

**Comment by martin-mosteiro** [comment] 2018-05-31 12:31
The following is an issue with the window-to-wall ratio specified for south-facing walls. Could you please supply us with your architecture.dbf file to check what the issue might be?
If you do not have one, then that is probably the reason for the issue. You might want to run the "Data helper" tool in order to create this file based on the CEA archetype database.
![40623633-692224bc-6297-11e8-9521-30163bbba2ee](https://user-images.githubusercontent.com/18548065/40782302-24679bdc-64df-11e8-8278-3fd29eae3eba.jpg)
![40623669-9422921e-6297-11e8-83d0-2ba6aeace389](https://user-images.githubusercontent.com/18548065/40782304-248e9854-64df-11e8-8db3-75c0299a8e69.jpg)

**Comment by martin-mosteiro** [comment] 2018-05-31 12:35
These issues all point to the following error: `No module named arcgisscripting`. This error could be caused by your PYTHONPATH variable not being set correctly. [These instructions](https://gis.stackexchange.com/questions/387/resolving-importerror-no-module-named-arcgisscripting) may help solve the problem.
![40623631-68bf36a4-6297-11e8-9523-46d6f6e1bf7c](https://user-images.githubusercontent.com/18548065/40782003-40583c4e-64de-11e8-89cf-995bc3a41f1a.jpg)
![40623667-93c9b7b6-6297-11e8-9e2f-f009bf1ed41c](https://user-images.githubusercontent.com/18548065/40782004-40708dc6-64de-11e8-864b-c942b62e7292.jpg)
![40623673-95c4211e-6297-11e8-9e61-1b284afb0133](https://user-images.githubusercontent.com/18548065/40782005-40879ae8-64de-11e8-8438-bf09a9601748.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:00
Basically I tried to run the latest version of the tool that is available on your website (CEA 2.7).
 I followed the order in the advanced tutorials section 
(http://city-energy-analyst.readthedocs.io/en/latest/tutorials.html). 
Starting with 
1.How does the Urban Solar Radiation tool work?.
Path to the scenario to run
C:\reference-case-open\baseline
IOError: no such file or directory: 'C:\\reference-case-open\\baseline\\inputs\\building-properties\\architecture.dbf'

C:\reference-case-open\baseline\inputs\building-geometry : This folder is empty
C:\reference-case-open\baseline\inputs\building-properties : This folder is empty

C:\reference-case\baseline\reference-case-open\baseline\inputs : This folder has 
"building-geometry, building-metering, building-properties, networks, topography, weather" folders.

**Comment by kerembeygo** [comment] 2018-05-31 20:03
C:\reference-case\baseline\reference-case-open\baseline\inputs\building-properties
[architecture.zip](https://github.com/architecture-building-systems/CityEnergyAnalyst/files/2059880/architecture.zip)
architecture.dbf file

**Comment by kerembeygo** [comment] 2018-05-31 20:07
![inputs building geometry](https://user-images.githubusercontent.com/29708612/40805562-2b114850-650e-11e8-9cc3-5e113794b1b4.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:08
![inputs building metering](https://user-images.githubusercontent.com/29708612/40805594-513a2326-650e-11e8-9da1-2290ded75559.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:08
![inputs building properties](https://user-images.githubusercontent.com/29708612/40805631-703e40c2-650e-11e8-8f90-1af757c9354b.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:09
![inputs networks](https://user-images.githubusercontent.com/29708612/40805691-95dca468-650e-11e8-8253-ba0c1c9364a2.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:10
![inputs topography](https://user-images.githubusercontent.com/29708612/40805713-af0b3d32-650e-11e8-8701-e4c1efe35f49.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:11
![inputs weather](https://user-images.githubusercontent.com/29708612/40805742-c98d57b2-650e-11e8-8641-ed2bff752a6c.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:15
A much earlier version of CEA was installed on PC. There was some problems with ArcScene 10.5. Problem was solved by Daren Thomas. I think that version is still on PC.

**Comment by kerembeygo** [comment] 2018-05-31 20:15
![two versions](https://user-images.githubusercontent.com/29708612/40805940-6825b040-650f-11e8-8fc4-ec8ef67491ac.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:41
Run for C:\reference-case-open\baseline
![reference case](https://user-images.githubusercontent.com/29708612/40807124-f984a0f2-6512-11e8-8435-5209fe7ff09d.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:43
![1](https://user-images.githubusercontent.com/29708612/40807225-3d3842ea-6513-11e8-83e3-e01a1173c410.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:44
![2](https://user-images.githubusercontent.com/29708612/40807289-6ab01784-6513-11e8-8132-a62ed3c081d1.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:46
![3](https://user-images.githubusercontent.com/29708612/40807357-9bc71aa2-6513-11e8-9e71-bfa327023477.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:49
Run for 
![4](https://user-images.githubusercontent.com/29708612/40807563-2aa0f3a6-6514-11e8-8127-6cbc52fb16ec.jpg)
C:\reference-case\baseline\reference-case-open\baseline

**Comment by kerembeygo** [comment] 2018-05-31 20:51
![5](https://user-images.githubusercontent.com/29708612/40807645-6e07e000-6514-11e8-93af-fa61759bcfb6.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:53
![6](https://user-images.githubusercontent.com/29708612/40807712-97a1b9e0-6514-11e8-9123-0007f2642339.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:54
![7](https://user-images.githubusercontent.com/29708612/40807779-c7f4fd3c-6514-11e8-9e90-47c04681e028.jpg)

**Comment by kerembeygo** [comment] 2018-05-31 20:56
Is there a way to clean both versions of CEA without leaving a trace? May be I should reinstall the newer version then...

**Comment by martin-mosteiro** [comment] 2018-06-01 09:28
@kerembeygo Interesting, you are indeed running an up-to-date case study, so I believe you probably do have conflicting versions of CEA installed and the toolbox that is installed on your ArcGIS is an older version.
I think @daren-thomas is probably the best person to assist you with installation issues.

**Comment by daren-thomas** [comment] 2018-06-01 10:58
@kerembeygo how did you install the CityEnergyAnalyst?

**Comment by kerembeygo** [comment] 2018-06-01 18:37
I used the Setup_CityEnergyAnalyst_2.7
![1](https://user-images.githubusercontent.com/29708612/40857495-dc9a8b38-65ca-11e8-903f-bc0cf18be24a.jpg)

**Comment by daren-thomas** [comment] 2018-06-15 09:38
@kerembeygo this is a very old version of the CEA. Could you try installing the research version instead?
Installation is a bit more involved, but explained in detail here:

- http://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html

**Closed** 2018-06-15 14:13 UTC

**Comment by kerembeygo** [comment] 2018-06-17 07:12
"Follow these instructions to install the CEA on a Windows system (tested with Windows 10)"
Does it work on Windows 8.1?

**Comment by daren-thomas** [comment] 2018-06-18 12:53
@kerembeygo it should, but we have not tested it.

**Comment by daren-thomas** [comment] 2018-06-18 12:53
we have tested on Windows 7, so... I'm pretty confident it will run on Windows 8.1.
