### ISSUE TITLE
MacOS-arm64 GUI - Error: Could not create CEA environment.

### ISSUE THREAD

**Issue by brynpickering** [architecture-building-systems/CityEnergyAnalyst#3593] opened 2024-05-28 10:42 UTC
**Describe the bug**
I have tried installing CEA (+ GUI) from the pre-built DMG _and_ following the [manual install instructions](https://city-energy-analyst.readthedocs.io/en/latest/installation/installation-on-macos.html).

In both instances, CEA installs just fine, but then encounters an error on startup: `Could not create CEA environment.`

**To Reproduce**
1. Install CEA on a macos-arm64 (i.e. Apple Silicon) device. 
2. Open the CEA-GUI app

**Screenshots**

<img width="502" alt="Screenshot 2024-05-28 at 11 39 53" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/17178478/765f8d2e-878a-40cf-9b1e-303ee4439f69">

**Hardware (please complete the following information):**
 - OS and version: macos-arm64 v14.4.1 
 - Version of CEA you are using: v3.36.0 & 6c1ca77

**Comment by reyery** [comment] 2024-05-28 11:40
Hi @brynpickering, thanks for reporting this issue to us. 
Unfortunately, we were not able to reproduce this error on our end. 
Could you let us know what is written in the logs found in `~/Library/Logs/CityEnergyAnalyst-GUI/main.log`.

**Comment by brynpickering** [comment] 2024-05-28 11:52
```python
[2024-05-28 12:47:58.597] [info]  CEA GUI version: 3.36.0
[2024-05-28 12:47:58.600] [info]  Checking for GUI update...
[2024-05-28 12:47:58.606] [info]  Checking for update
[2024-05-28 12:48:00.436] [info]  Update for version 3.36.0 is not available (latest version: 3.36.0, downgrade is disallowed).
[2024-05-28 12:48:00.449] [debug] {
  versionInfo: {
    tag: 'v3.36.0',
    version: '3.36.0',
    files: [
      {
        url: 'CityEnergyAnalyst-GUI-3.36.0-mac.zip',
        sha512: 'KK3eFxiNhoJl1co5VQxovw+nBdrp0xnJGda86UmnaSCBAv/nDcUNvZDlr/r+Gh/NLH1pKCsn/GJuBEO1ciQpyA==',
        size: 179491423
      },
      {
        url: 'CityEnergyAnalyst-GUI-3.36.0-arm64-mac.zip',
        sha512: '84LdWGzpt09HcmxD95flFocmJ20qlEvTot8eXfJGXMgwzOqUAMKeA+NAKuddIfo8JHvgf5mgzQBIBW/YJVTQKw==',
        size: 172480688
      },
      {
        url: 'CityEnergyAnalyst-GUI-3.36.0.dmg',
        sha512: 'bwURYdFl00IyUGlN6T8R+WylEn0PhhhGn3u+nOrmdf2iUc/BqD7gvsLXkSY2BYkdidx4p/Ajh3NaSH8qv+f9qg==',
        size: 186184010
      },
      {
        url: 'CityEnergyAnalyst-GUI-3.36.0-arm64.dmg',
        sha512: 'C5sJRfh7ytKFmIEPDLOrSmCGMdR8nPRexVynBbo7Z/TDD4iQf39Syx4t3nV3dTRiA/+K8/Ts+zkV2au+w0XEUA==',
        size: 179168311
      }
    ],
    path: 'CityEnergyAnalyst-GUI-3.36.0-mac.zip',
    sha512: 'KK3eFxiNhoJl1co5VQxovw+nBdrp0xnJGda86UmnaSCBAv/nDcUNvZDlr/r+Gh/NLH1pKCsn/GJuBEO1ciQpyA==',
    releaseDate: '2024-05-21T16:09:42.660Z',
    releaseName: '3.36.0',
    releaseNotes: ''
  }
}
[2024-05-28 12:48:00.462] [debug] isCEAAlive(http://127.0.0.1:5050)
[2024-05-28 12:48:00.506] [error] No Response
[2024-05-28 12:48:00.507] [info]  Checking for CEA environment...
[2024-05-28 12:48:00.514] [debug] {
  micromambaPath: '/Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/micromamba'
}
[2024-05-28 12:48:00.519] [error] Error: Unable to find path to micromamba.
    at getMicromambaPath (file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/cea/env.mjs:37:11)
    at checkCEAenv (file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/cea/env.mjs:82:11)
    at preflightChecks (file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/main.mjs:241:17)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async BrowserWindow.<anonymous> (file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/main.mjs:289:7)
[2024-05-28 12:48:00.524] [info]  Creating CEA environment (3.36.0)...
(this might take a few minutes)
[2024-05-28 12:48:00.537] [debug] { ceaPath: '/Users/bryn.pickering/Documents/CityEnergyAnalyst' }
[2024-05-28 12:48:00.540] [debug] {
  message: 'Fetching conda-lock.yml',
  condaLockUrl: 'https://raw.githubusercontent.com/architecture-building-systems/CityEnergyAnalyst/v3.36.0/conda-lock.yml',
  condaLockPath: '/Users/bryn.pickering/Documents/CityEnergyAnalyst/conda-lock.yml'
}
[2024-05-28 12:48:00.945] [debug] {
  micromambaPath: '/Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/micromamba'
}
[2024-05-28 12:48:00.946] [error] Error: Unable to find path to micromamba.
    at getMicromambaPath (file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/cea/env.mjs:37:11)
    at file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/cea/env.mjs:161:27
    at new Promise (<anonymous>)
    at createCEAenv (file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/cea/env.mjs:160:11)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async preflightChecks (file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/main.mjs:255:11)
    at async BrowserWindow.<anonymous> (file:///Applications/CityEnergyAnalyst-GUI.app/Contents/Resources/app.asar/electron/main.mjs:289:7)

```

**Comment by brynpickering** [comment] 2024-05-28 12:00
From the downloaded .dmg, the issue could be that it's getting confused between my `mamba` and `micromamba` install. I use `mambaforge` day-to-day, but have `micromamba` available for testing (and installing CEA, it turns out!)

**Comment by brynpickering** [comment] 2024-05-28 16:11
hmm, could be an SSL cert issue (although I don't _think_ this should be an issue as I have the env variable `NODE_EXTRA_CA_CERTS` set up to point at my corporate cert).

`cea dashboard` followed by loading the GUI works fine.

**Comment by reyery** [comment] 2024-05-29 11:25
I will close this issue for now. Let us know if you face any other issues.

**Closed by reyery** 2024-05-29 11:25 UTC
Labels: bug
