### ISSUE TITLE
weather_helper: Could not find weather file:

### ISSUE THREAD

**Issue by santhan999** [architecture-building-systems/CityEnergyAnalyst#3237] opened 2022-08-26 09:32 UTC
**weather_helper: Could not find weather file:**
I tried to load a neighbourhood in Sweden and it shows this error.

**Hardware**
 - Version: [Windows 11]
 - Version of CEA you are using [v. 2.31.1]

**Comment by lguilhermers** [comment] 2022-08-29 02:58
@santhan999 when you go inside the weather helper tool and click the drop down menu, do you see any option? If so, you can select one and try running the script again.

If not, you can:
a) Browse for weather file and include any .epw weather file (some are open source and can be found online)
b) Browse for weather file inside your installed CEA path:
`CityEnergyAnalyst\CityEnergyAnalyst\cea\databases\weather`

We also have some CEA tutorials that might be helpful: https://www.cityenergyanalyst.com/video-tutorials

**Comment by lguilhermers** [comment] 2022-09-05 02:01
Closing the issue for now, feel free to reopen if the problem is still there.

**Closed by lguilhermers** 2022-09-05 02:01 UTC
Labels: User Support
