### ISSUE TITLE
Qcsf in demand total not properly aggregated

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1285] opened 2018-05-10 02:23 UTC
![image](https://user-images.githubusercontent.com/16998305/39848872-18d95084-543c-11e8-8901-897fbcc3a11e.png)

**Comment by gabriel-happle** [comment] 2018-05-10 07:38
@shanshanhsieh as discussed this is not a bug. Please close this issue if no further action is required.

**Closed** 2018-05-10 07:39 UTC
Labels: Priority 1, easy peasy
