### ISSUE TITLE
As a user, I would like to model buildings with unoccupied spaces (e.g. basements)

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1700] opened 2018-11-27 08:56 UTC
Since the executive course, the definition for the occupied area in CEA changed from Af (the conditioned area) to the gross floor area (GFA). This was necessary for Singapore since there are occupied unconditioned spaces. However, buildings in the European context also have unoccupied, unconditioned spaces – basements, for example. So right now CEA assumes that there are people in these spaces, which can grossly overestimate the number of people in the building, the water demand, etc.

In order to solve this, a new parameter could be defined, the net floor area (NFA), such that we'd now have:
- Gross floor area (GFA) = entire floor area of the building
- Net floor area (NFA) = occupied floor area of the building (usually NFA < GFA)
- Conditioned floor area (Af) = floor area that is heated or cooled (in Singapore, usually Af<NFA).

**Comment by JIMENOFONSECA** [comment] 2018-11-27 09:42
Well, we moved to use GFA because it is more standard with the concept of end-use energy intensity. Which helps to cover more places worldwide.

However, I understand NFA is used for the 2000-Watt society and Minergie, which makes sense to a great extend.

Ideally we have both options. To me GFA just makes things easier to compare scenarios and several locations. and well, I believe we have more certainty in the GFA of a building due to its geometry than the NFA (based on thermal zones).

Kind regards,
Jimeno

_______________________

Dr. Jimeno A. Fonseca
Senior researcher & Project coordinator
Multi-scale energy systems for low-carbon cities
Singapore ETH-Centre

Product owner & Scrum master
City Energy Anlayst (CEA)<http://www.cityenergyanalyst.com>

Prof.h.c in modeling and simulation
Universidad Central de Colombia


On 27 Nov 2018, 5:29 PM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

One thing that I am still not sure about: should the plots still use GFA as the reference area? Or NFA? @JIMENOFONSECA<https://github.com/JIMENOFONSECA>, what do you think?

**Comment by martin-mosteiro** [comment] 2018-11-27 09:45
I don't think we actually do, because our calculation of GFA is very rough: ground floor geometry * number of floors. So if you take any building that is not shaped like a box, the whole calculation is off (e.g., what happens with a building where the size of the floor plan decreases with increasing height? then we grossly overestimate the GFA).
I think having a parameter like this NFA allows us to adjust for issues like that – which is basically what we had originally done with the conditioned floor area in the Hochschulquartier case study.

**Comment by JIMENOFONSECA** [comment] 2018-11-27 09:47
good point. So maybe we make the plots able to give both parameters energy/GFA and energy/NFA?

Jimeno


On 27 Nov 2018, 5:45 PM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

I don't think we actually do, because our calculation of GFA is very rough: ground floor geometry * number of floors. So if you take any building that is not shaped like a box, the whole calculation is off (e.g., what happens with a building where the size of the floor plan decreases with increasing height? then we grossly overestimate the GFA).
I think having a parameter like this NFA allows us to adjust for issues like that – which is basically what we had originally done with the conditioned floor area in the Hochschulquartier case study.

**Comment by martin-mosteiro** [comment] 2018-11-27 09:49
Yeah, that could be a good solution

**Comment by martin-mosteiro** [comment] 2018-11-27 10:10
Actually, rewriting all the plots would be quite a bit of additional work (because I would have to understand each of these scripts and so on) and it's not a priority for me. Perhaps it could be made into a separate issue for the future (labeled "Should have" and assigned to myself) @JIMENOFONSECA?

**Comment by JIMENOFONSECA** [comment] 2018-11-27 10:14
Sure,

 Probably, can we can also rename the issue so it states what the problem is? NFA visualisation in Plot….

On 27 Nov 2018, 6:10 PM +0800, Martín Mosteiro-Romero <notifications@github.com>, wrote:

Actually, rewriting all the plots would be quite a bit of additional work (because I would have to understand each of these scripts and so on) and it's not a priority for me. Perhaps it could be made into a separate issue for the future (labeled "Should have" and assigned to myself) @JIMENOFONSECA<https://github.com/JIMENOFONSECA>?

**Comment by martin-mosteiro** [comment] 2018-11-27 10:17
I think it's better to create a separate issue, since the issue I described here was a different one and much higher priority for me (and I've already fixed it and will create a PR soon).

**Comment by martin-mosteiro** [comment] 2018-11-27 12:38
Also worth noting, SIA 2024 values for electricity demand are given by *net* floor area, so in theory when using these values the electrified floor area should actually be equal to the net floor area, not 0.9*GFA as currently done on CEA.

**Comment by martin-mosteiro** [comment] 2018-11-27 13:29
Based on the above, I'm adding the parameter 'Es' back into the architecture.dbf file for case studies. I assume this might be a bit controversial :) But using an unreferenced general value of 0.9 for every building in the case study doesn't seem all that reasonable, either. This addition can easily be reverted if it were not approved, though.

**Comment by martin-mosteiro** [comment] 2018-11-27 13:36
On the positive side, since I have updated the example files, this issue should also solve #1698

**Closed** 2018-11-30 11:30 UTC
Labels: Must have, bug, enhancement
