### ISSUE TITLE
Config file is getting reset to default values after running scripts

### ISSUE THREAD

**Issue by BhargavaKrishnaSreepathi** [architecture-building-systems/CityEnergyAnalyst#1827] opened 2019-03-18 02:24 UTC
After running scripts, the `cea.config` present in the local computer is being reset to default values. This has been observed while running the `optimization_main.py` script, also while running few scripts in a different branch.

@shanshanhsieh:  you can add in your experience regarding the same.

@daren-thomas: Any idea why this is happening?

**Comment by daren-thomas** [comment] 2019-03-18 09:45
@BhargavaKrishnaSreepathi how do i reproduce this behavior? Can you please provide exact steps?

**Comment by BhargavaKrishnaSreepathi** [comment] 2019-03-18 12:16
1. For a cooling case study (take one of the singapore case studies).
2. Change the config file representing the cooling scenario. Make the flag `district-cooling-network` as `True`. Replace all the `DH` in the config file with `DC`. 
3. Save the config file and close it.
4. Run `cea\optimization\optimization_main.py` or run `cea\plots\optimization\main.py`. We observed the behaviour while we ran these scripts.

**Comment by daren-thomas** [comment] 2019-03-18 13:41
@BhargavaKrishnaSreepathi what exactly got changed? All the values? Some specific ones? How did you run the scripts?

**Comment by BhargavaKrishnaSreepathi** [comment] 2019-03-18 13:47
@daren-thomas: Everything in the `general` section of the config file got changed to default values. I ran the scripts from Pycharm (not the command prompt)

**Comment by JIMENOFONSECA** [comment] 2019-03-20 09:07
@daren-thomas I have the same problem when I run a new installation of CEA. all values get reset.

@daren-thomas I also see a quirky behaviour. When I do a fresh installation of CEA, I have to run a random program to make the cea.config show up. But should not it be ready after installing it?

**Comment by daren-thomas** [comment] 2019-03-20 09:20
@JIMENOFONSECA what exactly do you view as "run a new installation of CEA"? what are the steps?

regarding the `cea.config`: that is created on first access. We don't really have an installer. That's where this file would be created.

**Comment by JIMENOFONSECA** [comment] 2019-03-20 09:25
"run a new installation of CEA". I mean, I do a fresh installation of CEA.
________________________________

**Comment by daren-thomas** [comment] 2019-03-20 09:28
to clarify: you mean, follow the [installation guide](https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html) steps 1-10?

**Comment by JIMENOFONSECA** [comment] 2019-03-20 09:53
Sorry, I mean these two steps:


  *   Conda env update
  *   Pip install .[dev]

_______________________

Dr. Jimeno A. Fonseca
Senior researcher and project coordinator
Future cities Laboratory
Singapore ETH-Centre

On 20 Mar 2019, 17:28 +0800, Daren Thomas <notifications@github.com>, wrote:

to clarify: you mean, follow the installation guide<https://city-energy-analyst.readthedocs.io/en/latest/installation-on-windows.html> steps 1-10?

**Comment by daren-thomas** [comment] 2019-04-10 14:43
I can't reproduce this. I'm following the exact steps.

@shanshanhsieh were you testing on your computer? Could you try doing this in a python shell: `os.path.expanduser('~/cea.config')` - is that a local file on your computer?

**Comment by daren-thomas** [comment] 2019-04-18 09:19
Closing as not reproducible.

**Closed by daren-thomas** 2019-04-18 09:19 UTC
Labels: Must have, bug
