### ISSUE TITLE
Dependency on path "C:\\reference-case-open" for install-toolbox and extract-reference-case

### ISSUE THREAD

**Issue by Jack-Hawthorne** [architecture-building-systems/CityEnergyAnalyst#1755] opened 2019-01-22 17:45 UTC
The cea install-toolbox and cea extract-reference-case are both dependent on the existence of the ```C:\\reference-case-open```

```
(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst>cea install-toolbox
City Energy Analyst version 2.9.0
Running `cea install-toolbox` with the following parameters:
- general:debug = False
Traceback (most recent call last):
  File "C:\Users\Jack\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 59, in main
    locator=cea.inputlocator.InputLocator(config.scenario), region=config.region)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 47, in __getattr__
    return getattr(self.sections['general'], cid)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 237, in __getattr__
    return self.parameters[cid].get()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 330, in get
    encoded_value = self.replace_references(encoded_value)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 346, in replace_references
    encoded_value = re.sub('{([a-z0-9-]+):([a-z0-9-]+)}', lookup_config, encoded_value)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 344, in lookup_config
    return self.config.sections[matchobj.group(1)].parameters[matchobj.group(2)].get()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 332, in get
    return self.decode(encoded_value)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 624, in decode
    if str(value) in self._choices:
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 646, in _choices
    return [folder for folder in os.listdir(self.config.project)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\reference-case-open/*.*'
```

```
(cea) C:\Users\Jack\Documents\GitHub\CityEnergyAnalyst>cea extract-reference-case
City Energy Analyst version 2.9.0
Running `cea extract-reference-case` with the following parameters:
- extract-reference-case:destination = C:\
Traceback (most recent call last):
  File "C:\Users\Jack\Miniconda2\envs\cea\Scripts\cea-script.py", line 11, in <module>
    load_entry_point('cityenergyanalyst', 'console_scripts', 'cea')()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\interfaces\cli\cli.py", line 59, in main
    locator=cea.inputlocator.InputLocator(config.scenario), region=config.region)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 47, in __getattr__
    return getattr(self.sections['general'], cid)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 237, in __getattr__
    return self.parameters[cid].get()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 330, in get
    encoded_value = self.replace_references(encoded_value)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 346, in replace_references
    encoded_value = re.sub('{([a-z0-9-]+):([a-z0-9-]+)}', lookup_config, encoded_value)
  File "C:\Users\Jack\Miniconda2\envs\cea\lib\re.py", line 155, in sub
    return _compile(pattern, flags).sub(repl, string, count)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 344, in lookup_config
    return self.config.sections[matchobj.group(1)].parameters[matchobj.group(2)].get()
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 332, in get
    return self.decode(encoded_value)
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 624, in decode
    if str(value) in self._choices:
  File "c:\users\jack\documents\github\cityenergyanalyst\cea\config.py", line 646, in _choices
    return [folder for folder in os.listdir(self.config.project)
WindowsError: [Error 3] The system cannot find the path specified: 'C:\\reference-case-open/*.*'
```

This should probably be explicit in the installation steps or reviewed in both scripts.

**Comment by daren-thomas** [comment] 2019-01-23 14:06
possible duplicate of #1760

**Closed** 2019-02-04 10:09 UTC
Labels: Must have, bug
