### ISSUE TITLE
DLL issue: "Die Ordnungszahl 242 wurde in der DLL mkl_intel_thread.dll nicht gefunden"

### ISSUE THREAD

**Issue by wieselukas** [architecture-building-systems/CityEnergyAnalyst#2674] opened 2020-03-27 16:41 UTC
See the comments on this issue for more information - basically, @wieselukas can't start the CEA GUI due to some incompatibility of DLL's on his system, probably due to the mkl_intel_* family of DLLs. We're not quite sure yet how to fix.

## Previous bug: (solve _after_ above works)

Title: Error loading weather file when creating a scenario

**Describe the bug**
After pressing "safe" on the Create new scenario screen I get the following error:

ERROR: weather_helper: Could not find weather file:
Details:
```
Traceback (most recent call last):
  File "C:\Users\wiese\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\api\project.py", line 197, in post
    cea.api.weather_helper(config, scenario=new_scenario_path)
  File "C:\Users\wiese\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 52, in __call__
    self._runner.__call__(*args, **kwargs)
  File "C:\Users\wiese\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\api.py", line 32, in script_runner
    script_module.main(config)
  File "C:\Users\wiese\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\weather_helper.py", line 53, in main
    copy_weather_file(config.weather_helper.weather, locator)
  File "C:\Users\wiese\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\datamanagement\weather_helper.py", line 31, in copy_weather_file
    source_weather_file=source_weather_file
AssertionError: Could not find weather file: 
```

This happens no matter if I select a weather file contained within CEA or I select the path to a weather file downloaded from EnergyPlus in the .epw format.
When not selecting a weather file on the "Create Scenario" Screen I'm afterwards not able to perform any analysis (the jobs get stuck being in state pending) which I believe is because of the missing weather file.

This is my first time trying to use the software so I'm not sure whether I did everything correctly, but of course followed the available docs and how-to's as closely as possible.

**To Reproduce**
1. Click "Create new Scenario" on the Project Overview Page
2. Select "Generate new input files using tools"
3. check all the boxes below
4. open the "Weather helper" window by clicking on the gear icon next to "Weather"
5. Select your desired area
6. Click on "Create"
7. after a few seconds the described error shows up

**Hardware (please complete the following information):**
 - OS and version: Windows 10 Pro N (10.0.17763 Build 17763)
 - Version of CEA: CEA V3.0.2

**Comment by reyery** [comment] 2020-03-28 03:41
@wieselukas I was not able to reproduce the error on my end, maybe you can try the following and let me know if it works.

Based on the error you have provided, it could be that there was no weather file selected. May I know if you have clicked the **Save & Close** button after setting the weather?

![image](https://user-images.githubusercontent.com/34395415/77813761-2132fc80-70e6-11ea-8fae-390520d4158a.png)

Besides that, jobs should still run and not stay in `pending` even if the weather file is missing (though those that need the weather file would fail). That bug sounds like something that was happening in v3.0.1 that was fixed in v3.0.2. May I know where did you download the CEA installer? And could you try opening **CEA Console** (installed with CEA) and type `cea --version` to confirm the version that was installed.

That would help me narrow down the issue. Thanks

**Comment by wieselukas** [comment] 2020-03-30 08:33
Thank you for your fast reply!

1. Yes I did press "Save & Close" to end the dialog
2. I downloaded the Setup_CityEnergyAnalyst_3.0.2.exe from the cea website (https://cityenergyanalyst.com/try-cea)
3. when running cea --version I get (as expected from my side): City Energy Analyst version 3.0.2

Something seems to be odd on my computer. This morning I wanted to recreate the issue and the CEA Dashboard would not start at all (showing the error message below). 
![CEA_Error](https://user-images.githubusercontent.com/13906846/77891298-080a8700-7271-11ea-8416-bc8435fd32ad.PNG)
To fix it I reinstalled CEA now using the executable from github (v3.0.2). I also made shure to run the installation executable as admin to prevent any issues with access rights. When trying to open the CEA Dashboard now, the error message from the image above still shows up after some seconds (same issue as before the re-install).

This unfortunately is not related to my problem of loading the weather file from before, but prevents me from recreating the weather file problem.

**Comment by shanshanhsieh** [comment] 2020-04-02 09:53
@reyery will test the new version v3.0.2

**Comment by wieselukas** [comment] 2020-04-02 10:06
Is there a better tested version from the past I could try in the meanwhile?

**Comment by reyery** [comment] 2020-04-06 21:55
Hmm.. there could be something wrong with just the GUI. 

Could you try downloading just the GUI files [here](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.0.2/win-unpacked.7z) and extract to overwrite the one that you have.

![image](https://user-images.githubusercontent.com/34395415/78608762-0c97f680-7894-11ea-8644-9b3838ae6b8f.png)

In the meantime, I will try to recreate the problem on my end.

**Comment by wieselukas** [comment] 2020-04-08 08:41
When Starting the dashboard over the console I get the following error:

![CEA_Error_from_console](https://user-images.githubusercontent.com/13906846/78762957-dbe3ba00-7984-11ea-9d25-2a40b2c34cb6.PNG)
(Roughly translated: The ordinal number 242 was not found in the library "[...]")

When trying version 3.0.1 I got exactly the both same errors when starting from the dashboard icon and the console. 

Is there the possibility to enable logging or get the installation logfile?

**Comment by reyery** [comment] 2020-04-08 11:53
Hmm.. In that case, it seems that this problem might not be caused by CEA but python itself. Do you have any other python/conda installations on your machine?

**Comment by wieselukas** [comment] 2020-04-08 14:01
No just the one that got installed by the cea installer.

It puzzles me why the error occured after the weekend but did not occur before the weekend. Maybe as background knowledge it's usefull to know that Germany changed to DST over especially this weekend. But I don't know if that could have to do with the error I get.

**Comment by reyery** [comment] 2020-04-09 11:36
Hey @wieselukas, I think I might have discovered something that might solve this. According to [this](https://conda.io/projects/conda/en/latest/user-guide/troubleshooting.html#numpy-mkl-library-load-failed) documentation, it could be that some other application installed Intel libraries to C:\Windows\System32 on your computer that is not compatible with CEA.

To solve this you could try to edit the **dashboard.bat** file found in the CEA installation path and add this line `SET CONDA_DLL_SEARCH_MODIFICATION_ENABLE=1` above the last line.


![image](https://user-images.githubusercontent.com/34395415/78890930-1dfe2000-7a99-11ea-8fdd-6fee91cb54f0.png)

![image](https://user-images.githubusercontent.com/34395415/78891013-3d954880-7a99-11ea-8e29-e8c1d4354de1.png)

Let me know if that works.

**Comment by wieselukas** [comment] 2020-04-20 09:02
I tried adding the line like you said and had no success on both my at the time installed version 3.0.1 and also after installing the newly released 3.1.0 version. The error messages remained the same when starting the cea dashboard from the console or the desktop icon.

**Comment by reyery** [comment] 2020-04-28 11:49
All right, in addition to that line, add 
> `C:\Users\Admin\Documents\CityEnergyAnalyst\Dependencies\Python\Library\bin;` 

to the front of **PATH** 
(edit the path according to the path of your CEA installation directory i.e. `$CEA_PATH\Dependencies\Python\Library\bin;`)

![image](https://user-images.githubusercontent.com/34395415/80483414-a2510e00-8988-11ea-9f12-b1fa72a66866.png)

Hopefully this would allow python to search for the DLLs in there first.

**Comment by daren-thomas** [comment] 2020-05-04 06:14
@wieselukas did this help with your error?

**Comment by wieselukas** [comment] 2020-05-05 08:29
I tried the suggested addition to the dashboard.bat file but still get the same error-messages

**Comment by reyery** [comment] 2020-05-11 23:01
@wieselukas could you check if the file `mkl_intel_thread.dll` is located in `C:\Windows\System32`? If so, could you try uploading the file. I would need to try to reproduce this error on my end to solve it.

**Comment by daren-thomas** [comment] 2020-05-25 07:43
@wieselukas, we're closing this issue as not reproducible. We're deeply sorry you had this experience with the CEA. We'd love to help fix it for you and will re-open this issue if you want to give it another shot.

**Closed** 2020-05-25 07:43 UTC
Labels: Must have, bug
