### ISSUE TITLE
Error using building solar radiation 

### ISSUE THREAD

**Issue by metwaly-ali** [architecture-building-systems/CityEnergyAnalyst#3239] opened 2022-08-28 07:53 UTC
1 - ( Describe the case you are trying to run ) : I want work run script to building solar radiation  for the data on the program so I can change the numbers to fit my project.
2- ( Describe the steps you performed leading up to the error ) : Enter Data ( shapefiles ( road - zone - surrounfdin - terrian ) and then Demand forecasting  and then building solar radiation and then Advanced ( daysim binaries under Dependencies -> Daysim. Once you find the Daysim folder replace the 'daysim-bin-directory' parameter here with the directory of that folder )  to run script .

3- Provide the detailed error message that is CEA prompts ( status: ERROR
parameters:
{
  "scenario": "C:\\Users\\User\\Aswan project\\urban form",
  "multiprocessing": true,
  "buildings": [
    "B1000",
    "B1001",
    "B1002",
    "B1003",
    "B1004",
    "B1005",
    "B1006",
    "B1007",
    "B1008",
    "B1009",
    "B1010",
    "B1011",
    "B1012",
    "B1013",
    "B1014",
    "B1015",
    "B1016",
    "B1017",
    "B1018",
    "B1019",
    "B1020",
    "B1021",
    "B1022",
    "B1023",
    "B1024",
    "B1025",
    "B1026",
    "B1027",
    "B1028",
    "B1029",
    "B1030",
    "B1031",
    "B1032",
    "B1033",
    "B1034",
    "B1035",
    "B1036",
    "B1037",
    "B1038",
    "B1039",
    "B1040",
    "B1041",
    "B1042",
    "B1043",
    "B1044",
    "B1045",
    "B1046",
    "B1047",
    "B1048",
    "B1049",
    "B1050",
    "B1051",
    "B1052",
    "B1053",
    "B1054",
    "B1055",
    "B1056",
    "B1057",
    "B1058",
    "B1059",
    "B1060",
    "B1061",
    "B1062",
    "B1063",
    "B1064",
    "B1065",
    "B1066",
    "B1067",
    "B1068",
    "B1069",
    "B1070",
    "B1071",
    "B1072",
    "B1073",
    "B1074",
    "B1075",
    "B1076",
    "B1077",
    "B1078",
    "B1079",
    "B1080",
    "B1081",
    "B1082",
    "B1083",
    "B1084",
    "B1085",
    "B1086",
    "B1087",
    "B1088",
    "B1089",
    "B1090",
    "B1091",
    "B1092",
    "B1093",
    "B1094",
    "B1095",
    "B1096",
    "B1097",
    "B1098",
    "B1099",
    "B1100",
    "B1101",
    "B1102",
    "B1103",
    "B1104",
    "B1105",
    "B1106",
    "B1107",
    "B1108",
    "B1109",
    "B1110",
    "B1111",
    "B1112",
    "B1113",
    "B1114",
    "B1115",
    "B1116",
    "B1117",
    "B1118",
    "B1119",
    "B1120",
    "B1121",
    "B1122",
    "B1123",
    "B1124",
    "B1125",
    "B1126",
    "B1127",
    "B1128",
    "B1129",
    "B1130"
  ],
  "use-latest-daysim-binaries": true,
  "albedo": "0.2",
  "number-of-cpus-to-keep-free": "1",
  "debug": false,
  "daysim-bin-directory": "C:\\Users\\User\\Documents\\METO WORK\\CityEnergyAnalyst\\Dependencies\\Daysim",
  "n-buildings-in-chunk": "100",
  "write-sensor-data": true,
  "roof-grid": "10",
  "walls-grid": "200",
  "zone-geometry": "2",
  "surrounding-geometry": "5",
  "consider-floors": true,
  "consider-intersections": false,
  "rad-ab": "4",
  "rad-ad": "512",
  "rad-as": "32",
  "rad-ar": "20",
  "rad-aa": "0.15",
  "rad-lr": "8",
  "rad-st": "0.5",
  "rad-sj": "0.7",
  "rad-lw": "0.05",
  "rad-dj": "0.7",
  "rad-ds": "0",
  "rad-dr": "0",
  "rad-dp": "32"
} ) 
4- Provide input files that are located in the input folder of your script ( https://drive.google.com/file/d/1L3lhu09DlyF8WYAdWTIg4UK-bM-ViPjv/view?usp=sharing )

**Comment by lguilhermers** [comment] 2022-08-29 03:25
@metwaly-ali the information you included is just the parameters of you simulation, not a simulation error.

I suggest you re-watch the tutorials and follow each step, changing it to your area of interest. This should definetly work.
If for some reason this still doesn't work, you may test another few different areas to see if any of them run. This will also make you more familiar with the software before moving to more complex cases.

By quickly looking at your files I see that they don't have their original names and are not in the original folder structure.
The program will not read those files and therefore the simulation will not work. If you follow the tutorial steps, you don't need to worry about file names and/ or filder structures.

Tutorials avalable here here: https://www.cityenergyanalyst.com/video-tutorials

**Closed** 2022-08-29 03:27 UTC
Labels: bug

**Comment by metwaly-ali** [comment] 2022-09-06 00:48
I really followed what I said, but the problem still exists... I want to answer this question is does the data need to be known on open street map so we can simulate and no data can any area even if it is not known on open street map????????????????????/

**Comment by lguilhermers** [comment] 2022-09-06 00:54
Hi. Yes, you need open street maps to have at least the building footprints in order to create a scenario. I suggest you try some other locations (including other countries), even if you are not interested in those areas in particular, just to see if they work.
From that you can try to discover if the problem is in all your simulations or just this partuicular site.

If you want to send me the location on google maps of the area you are trying to run, I can try to see if there might be a data problem there.

**Comment by metwaly-ali** [comment] 2022-09-06 01:12
ok 
https://www.cityenergyanalyst.com/video-tutorials
The files I entered into the program and I worked and applied like what was applied in the annotation videos... If any yarrett problem you say a need is necessary

**Comment by lguilhermers** [comment] 2022-09-06 01:18
Sorry, I did not understand your message..
If you want to send the location you are trying to run I can check if there is any problem with this area.
Otherwise, I am afraid we are unable to assist further, I am sorry about that.

**Comment by metwaly-ali** [comment] 2022-09-06 01:30
ok
https://goo.gl/maps/angSMmEAnUpa9mFM8
The study area is here.

**Comment by lguilhermers** [comment] 2022-09-06 01:51
@metwaly-ali I tested this area but there are not many buildings:
![image](https://user-images.githubusercontent.com/50981039/188529570-95edd31f-396c-4f99-90e8-9defe826b812.png)

If the area is too small and doesn't find any building, you will get errors.
If this looks good for you, you can just try to select a large area and it should work, as it worked for me.

Here are some other options you can consider:

- Change your study to somewhere with enough data (Cairo, for example, seems to work well)
- Add data  directly to Open Street Maps so CEA can read it
- Use other areas to become familiar with CEA in other areas and then add your own geometry when you are more comfortable with it (https://www.cityenergyanalyst.com/blog-posts/2021/01/20/2021-1-20-how-to-add-own-building-geometries-to-a-scenario-import-of-manually-created-shapefiles)

**Comment by metwaly-ali** [comment] 2022-09-06 02:09
![image](https://user-images.githubusercontent.com/110869501/188532014-b702a069-3607-4fb0-9eec-b8f0a3d0db6f.png)
jobID: 16 - radiation
status: ERROR
parameters:
{
  "scenario": "C:\\Users\\User\\Aswan project\\metoo",
  "multiprocessing": true,
  "buildings": [
    "B1000",
    "B1001",
    "B1002",
    "B1003",
    "B1004",
    "B1005",
    "B1006",
    "B1007",
    "B1008",
    "B1009",
    "B1010",
    "B1011",
    "B1012",
    "B1013",
    "B1014",
    "B1015",
    "B1016",
    "B1017",
    "B1018",
    "B1019",
    "B1020",
    "B1021",
    "B1022",
    "B1023",
    "B1024",
    "B1025",
    "B1026",
    "B1027",
    "B1028",
    "B1029",
    "B1030",
    "B1031",
    "B1032",
    "B1033",
    "B1034",
    "B1035",
    "B1036",
    "B1037",
    "B1038",
    "B1039",
    "B1040",
    "B1041",
    "B1042",
    "B1043",
    "B1044",
    "B1045",
    "B1046",
    "B1047",
    "B1048",
    "B1049",
    "B1050",
    "B1051",
    "B1052",
    "B1053",
    "B1054",
    "B1055",
    "B1056",
    "B1057",
    "B1058",
    "B1059",
    "B1060",
    "B1061",
    "B1062",
    "B1063",
    "B1064",
    "B1065",
    "B1066",
    "B1067",
    "B1068",
    "B1069",
    "B1070",
    "B1071",
    "B1072",
    "B1073",
    "B1074",
    "B1075",
    "B1076",
    "B1077",
    "B1078",
    "B1079",
    "B1080",
    "B1081",
    "B1082",
    "B1083",
    "B1084",
    "B1085",
    "B1086",
    "B1087",
    "B1088",
    "B1089",
    "B1090",
    "B1091",
    "B1092",
    "B1093",
    "B1094",
    "B1095",
    "B1096",
    "B1097",
    "B1098",
    "B1099",
    "B1100",
    "B1101",
    "B1102",
    "B1103",
    "B1104",
    "B1105",
    "B1106",
    "B1107",
    "B1108",
    "B1109",
    "B1110",
    "B1111",
    "B1112",
    "B1113",
    "B1114",
    "B1115",
    "B1116",
    "B1117",
    "B1118",
    "B1119",
    "B1120",
    "B1121",
    "B1122",
    "B1123",
    "B1124",
    "B1125",
    "B1126",
    "B1127",
    "B1128",
    "B1129",
    "B1130",
    "B1131",
    "B1132",
    "B1133",
    "B1134",
    "B1135",
    "B1136",
    "B1137",
    "B1138",
    "B1139",
    "B1140",
    "B1141",
    "B1142",
    "B1143",
    "B1144",
    "B1145",
    "B1146",
    "B1147",
    "B1148",
    "B1149",
    "B1150",
    "B1151",
    "B1152",
    "B1153",
    "B1154",
    "B1155",
    "B1156",
    "B1157",
    "B1158",
    "B1159",
    "B1160",
    "B1161",
    "B1162",
    "B1163",
    "B1164",
    "B1165",
    "B1166",
    "B1167",
    "B1168",
    "B1169",
    "B1170",
    "B1171",
    "B1172",
    "B1173",
    "B1174",
    "B1175",
    "B1176",
    "B1177",
    "B1178",
    "B1179",
    "B1180",
    "B1181",
    "B1182",
    "B1183",
    "B1184",
    "B1185",
    "B1186",
    "B1187",
    "B1188",
    "B1189",
    "B1190",
    "B1191",
    "B1192",
    "B1193",
    "B1194",
    "B1195",
    "B1196",
    "B1197",
    "B1198",
    "B1199",
    "B1200",
    "B1201",
    "B1202",
    "B1203",
    "B1204",
    "B1205",
    "B1206",
    "B1207",
    "B1208",
    "B1209",
    "B1210",
    "B1211",
    "B1212",
    "B1213",
    "B1214",
    "B1215",
    "B1216",
    "B1217",
    "B1218",
    "B1219",
    "B1220",
    "B1221",
    "B1222",
    "B1223",
    "B1224",
    "B1225",
    "B1226",
    "B1227",
    "B1228",
    "B1229",
    "B1230",
    "B1231",
    "B1232",
    "B1233",
    "B1234",
    "B1235",
    "B1236",
    "B1237",
    "B1238",
    "B1239",
    "B1240",
    "B1241",
    "B1242",
    "B1243",
    "B1244",
    "B1245",
    "B1246",
    "B1247",
    "B1248",
    "B1249",
    "B1250",
    "B1251",
    "B1252",
    "B1253",
    "B1254",
    "B1255",
    "B1256",
    "B1257",
    "B1258",
    "B1259",
    "B1260",
    "B1261",
    "B1262",
    "B1263",
    "B1264",
    "B1265",
    "B1266",
    "B1267",
    "B1268",
    "B1269",
    "B1270",
    "B1271",
    "B1272",
    "B1273",
    "B1274",
    "B1275",
    "B1276",
    "B1277",
    "B1278",
    "B1279",
    "B1280",
    "B1281",
    "B1282",
    "B1283",
    "B1284"
  ],
  "use-latest-daysim-binaries": true,
  "albedo": "0.2",
  "number-of-cpus-to-keep-free": "1",
  "debug": false,
  "daysim-bin-directory": "C:\\Users\\User\\Documents\\METO WORK\\CityEnergyAnalyst\\Dependencies\\Daysim\\bin",
  "n-buildings-in-chunk": "100",
  "write-sensor-data": true,
  "roof-grid": "10",
  "walls-grid": "200",
  "zone-geometry": "2",
  "surrounding-geometry": "5",
  "consider-floors": true,
  "consider-intersections": false,
  "rad-ab": "4",
  "rad-ad": "512",
  "rad-as": "32",
  "rad-ar": "20",
  "rad-aa": "0.15",
  "rad-lr": "8",
  "rad-st": "0.5",
  "rad-sj": "0.7",
  "rad-lw": "0.05",
  "rad-dj": "0.7",
  "rad-ds": "0",
  "rad-dr": "0",
  "rad-dp": "32
.................................
I worked now and changed the area, but the problem still exists.

**Comment by metwaly-ali** [comment] 2022-09-06 02:15
I can get into LinkZoom with each other because I can't apply to the program until I've been swept. please please

**Comment by lguilhermers** [comment] 2022-09-06 02:23
@metwaly-ali good, we have some buildings now :)
there is no need to paste the simulation parameters, only the error message.
I see in the picture there is a warning about the Daysim binaries, I think that would have been helpful 
![image](https://user-images.githubusercontent.com/50981039/188532694-22558c55-f5df-4c61-bd55-1335b719a763.png)
for next times, you can click on it and send this message instead.

On the error:
On your radiation box and advanced settings, check daysim-bin-directory.
check the path that is shown to the Daysim binaries and, it should look like this:
`C:\Users\<put your user name here>\Documents\CityEnergyAnalyst\Dependencies\Daysim`
If the path is not that, try clicking the blue Default button to restore the settings or change manually.

When you open this folder on your computer, it should look like this:
![image](https://user-images.githubusercontent.com/50981039/188533137-169d81c7-4128-4652-bd95-2cea68f80bce.png)
Make sure you are finding this path and the simulation should work.

**Comment by metwaly-ali** [comment] 2022-09-06 02:30
![image](https://user-images.githubusercontent.com/110869501/188534339-f4a00897-01f7-4835-ad66-d1a375c49a58.png)
![image](https://user-images.githubusercontent.com/110869501/188534376-19e51d96-3096-45da-84c7-8aed50625702.png)
![image](https://user-images.githubusercontent.com/110869501/188534403-3d085b44-dc2b-429c-aa4d-851142d294e0.png)
The problem remains

**Comment by lguilhermers** [comment] 2022-09-06 02:34
Can you zip your project and send here via wetransfer?
I will try to take a look this week and run radiation on my version.

**Comment by metwaly-ali** [comment] 2022-09-06 02:43
https://drive.google.com/file/d/1nC1q65hkc4l5LjyZDb5mTi946Nuu5mBB/view?usp=sharing
Thank you very much and you can send me as soon as possible.

**Comment by lguilhermers** [comment] 2022-09-06 03:36
@metwaly-ali what I would need is the project/scenario you are working with. You have sent me just the CEA database.
You have to find the path that contains your CEA projects, and find the _Aswaan project_ and scenario _metoo_ in your case, with the buildings you just created on the image above.

Inside the scenario folder, it should have an inputs folder with multiple folders inside.
Without all this information, I can't test on my side.

**Comment by metwaly-ali** [comment] 2022-09-06 22:40
https://drive.google.com/file/d/1hrQCA3Pu1z2YZQqsKgs5-2EA3jnioVtL/view?usp=sharing
Thank you very much and you can send me as soon as possible.

**Comment by lguilhermers** [comment] 2022-09-07 05:14
@metwaly-ali 
I was able to start running radiation for your metoo scenario without any errors, so I can confirm it is not a bug on CEA.
![image](https://user-images.githubusercontent.com/50981039/188793642-d7ec9c5e-1288-4c67-85af-77773840474d.png)

If you want to keep trying, I recommend you uninstall CEA and reinstall it, to make sure all the packages are imported properly. 
Hopefully this would solve the issue.

**Comment by metwaly-ali** [comment] 2022-09-09 00:01
Thank you very much. I'll do that. If there's a problem, I'll talk to you.

**Comment by metwaly-ali** [comment] 2022-09-09 22:43
You can reply higher if you let me need to apply because of the doctoral thesis...........please

**Comment by kholody** [comment] 2022-09-12 22:50
Dear @lguilhermers 

It is such a helpful assist that you gave us here regarding this critical issue.
As for me, I still find it so confusing not to be able to proceed with my analysis using your wonderful Programme CEA .
Lately, I stopped at the same point when trying to apply for another area in Cairo also, and I followed all your recommendations but, I am afraid it did not work either >>\

Hopefully, I ask for your support for the last time as you may be busy ( as i am in the middle of my Research paper) , and I am really appreciating your help.
Could it possible to give us the specific steps of applying the scenario (on the area that "Dr. Metwalli " sent before) and how we can proceed to the final results applying all the analysis by CEA?

Thanks a lot for your precious time 
and hope to hear from you so soon

Regards 

Kholoud Farahat

   Kholoud Yahia Zakaria Mohammed Hassan (TA)  
  PHD candidate 
 Teaching Assistance at Faculty of Urban & Regional Planning - Cairo University 
 Tel: (+020)1111291145 
 E-mail: kholodkhokha99.ky@cu.edu.eg
