### ISSUE TITLE
Error displaying the dashboards dashboard 

### ISSUE THREAD

**Issue by emanuel030** [architecture-building-systems/CityEnergyAnalyst#2708] opened 2020-04-27 06:03 UTC
When opening the dashboard with any scenario and opening up the dashboard option from the menu on the left, no options of displaying the results are available. As in 'Add dashboard'
etc. are not available.

Following error message is shown when inspecting the page:

![image](https://user-images.githubusercontent.com/26175926/80338799-d72d6a00-888f-11ea-98aa-1b1109d49531.png)

**Hardware :**
 - OS and version: Windows 10
 - City Energy Analyst version 3.1.0 (master branch)

**Comment by reyery** [comment] 2020-04-28 10:14
Hmm.. I was not able to reproduce this error. Could you try to overwrite the GUI files by downloading it from here https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.1.0/win-unpacked.7z ?

**Comment by shanshanhsieh** [comment] 2020-04-29 07:21
@emanuel030 we are closing this issue, we can re-open it if @reyery's solution doesnt work.

**Closed by shanshanhsieh** 2020-04-29 07:21 UTC
Labels: bug

**Comment by emanuel030** [comment] 2020-04-29 09:47
Thank you both and sorry for the late reply! It worked with the proposed solution. I don't know what went wrong with the GUI since it worked before and then suddenly stopped. But is now fixed :)
