### ISSUE TITLE
CEA tests don't run 

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1987] opened 2019-05-21 03:56 UTC
Console tests stop after calibration. `dodo` on pycharm continues running.

CONSOLE OUTPUT:

```
...
>Metropolis: [var2]
>Metropolis: [var1]
100%|##############################################################################################################################| 1100/1100 [00:07<00:00, 151.45it/s] 100%|##############################################################################################################################| 1100/1100 [00:05<00:00, 213.26it/s] The number of effective samples is smaller than 25% for some parameters.
This application failed to start because it could not find or load the Qt platform plugin "windows"
in "".

Reinstalling the application may fix this problem.
```

PYCHARM OUTPUT:

```
...
>Metropolis: [var2]
>Metropolis: [var1]
100%|##########| 1100/1100 [00:06<00:00, 170.20it/s]
100%|##########| 1100/1100 [00:05<00:00, 212.48it/s]
The gelman-rubin statistic is larger than 1.05 for some parameters. This indicates slight problems during sampling.
The number of effective samples is smaller than 25% for some parameters.
.  run_emissions_operation:open
.  run_thermal_network

...
```

**Comment by gabriel-happle** [comment] 2019-05-21 06:06
Actually, I take it back. After pointing pycharm to the environment created with the installer, the `dodo` does not work either.

**Comment by gabriel-happle** [comment] 2019-05-21 06:11
output from pycharm in master

```
.  run_calibration
Only 100 samples in chain.
Sequential sampling (2 chains in 1 job)
CompoundStep
>Metropolis: [sigma]
>Metropolis: [var6]
>Metropolis: [var5]
>Metropolis: [var4]
>Metropolis: [var3]
>Metropolis: [var2]
>Metropolis: [var1]
100%|##########| 1100/1100 [00:09<00:00, 111.20it/s]
100%|##########| 1100/1100 [00:05<00:00, 191.50it/s]
The number of effective samples is smaller than 10% for some parameters.

Process finished with exit code 1
```

**Comment by daren-thomas** [comment] 2019-05-22 07:19
```
calculating thermal hydraulic properties of DH network  ...  time step 179
calculating thermal hydraulic properties of DH network  ...  time step 183
calculating thermal hydraulic properties of DH network  ...  time step 190
calculating thermal hydraulic properties of DH network  c.alculating thermal hydraulic properties of..  time step  D175H
 network  ...  time step 193
calculating thermal hydraulic properties of DH network  ...  time step 187
calculating thermal hydraulic properties of DH network  ...  time step 196
calculating thermal hydraulic properties of DH network  ...  time step 191
calculating thermal hydraulic properties of DH network  ...  time step 194
calculating thermal hydraulic properties of DH network  ...  time step 197
calculating thermal hydraulic properties of DH network  ...  time step 195
calculating thermal hydraulic properties of DH network  ...  time step 198
calculating thermal hydraulic properties of DH network  ...  time step 199
.  run_sensitivity
.  run_unit_tests
...........................
----------------------------------------------------------------------
Ran 27 tests in 75.869s

OK
```

this was from command line. worked for me.

**Comment by daren-thomas** [comment] 2019-05-22 07:26
@gabriel-happle i'm not really sure this is a blocking issue. the tests have been running for master on the jenkins too, so it might be more something with your setup?

**Comment by gabriel-happle** [comment] 2019-05-22 08:44
@daren-thomas My setup is a completely new installation with the installer. Incl. new python environment.
Doesn't that mean the master (and/or installer) is broken?

**Comment by daren-thomas** [comment] 2019-05-22 09:08
@gabriel-happle, i'll test it in a clean vm and report back. thank you for bringing this up.

**Comment by daren-thomas** [comment] 2019-05-22 09:42
Reproduced the error on a clean vm. Investigating.

**Comment by daren-thomas** [comment] 2019-05-22 10:16
Initial tests with setting "QT_PLUGIN_PATH" in the CEA Console to "C:\Users\USER\CityEnergyAnalyst\Dependencies\Python\Library\plugins" seems to fix it when running `cea test` from the CEA Console. Next step is to figure out how to add that for PyCharm and the CEA Desktop scenario.

**Comment by daren-thomas** [comment] 2019-05-22 12:08
![image.png](https://images.zenhubusercontent.com/57b40957e40e5714b16d7331/2b084f66-28f6-41f4-a987-fcc607989c1b)

It seems, when setting the "QT_PLUGIN_PATH" environment variable in the CEA Console, running `cea test` runs through. So this seems to be the issue. As far as I know, there might be problems with setting this as part of the installation for the user (problems with other software) so I'll look for a solution that does this in code.

**Comment by daren-thomas** [comment] 2019-05-22 12:10
Current workaround until I can solve this issue:

(in the CEA Console, type:)

```
set QT_PLUGIN_PATH=C:\Users\USER\CityEnergyAnalyst\Dependencies\Python\Library\plugins
cea test
```

(of course, replace USER with your username)

**Comment by daren-thomas** [comment] 2019-05-22 12:30
After more digging, I found the installer includes a `Dependencies\Python\qt.conf` file which should be updated when installing. The contents (as installed) are:

```
[Paths] 
Prefix = C:/Users/darthoma/Miniconda2/envs/cea/Library 
Binaries = C:/Users/darthoma/Miniconda2/envs/cea/Library/bin 
Libraries = C:/Users/darthoma/Miniconda2/envs/cea/Library/lib 
Headers = C:/Users/darthoma/Miniconda2/envs/cea/Library/include/qt
```

**Comment by daren-thomas** [comment] 2019-05-22 13:21
https://www.dropbox.com/s/cgf9jkcaikzo618/Setup_CityEnergyAnalyst_2.14.exe?dl=0

The above installer should fix this problem. I'm running some tests (local and in vm) to verify, but will create a PR as soon as that's done.

@gabriel-happle please test the installer on your computer to see if it solves the problem for you too.

**Comment by daren-thomas** [comment] 2019-05-23 07:38
This is now fixed. Users of releases 2.14 and before can re-run the 2.14 installer from GitHub to fix this.

**Comment by gabriel-happle** [comment] 2019-05-23 09:15
@daren-thomas should I close this? do you want to keep it open or post it somewhere for everyone?

**Closed** 2019-05-23 14:14 UTC
Labels: Must have, bug
