### ISSUE TITLE
Too low node supply temperatures in reference case open demand

### ISSUE THREAD

**Issue by roglen** [architecture-building-systems/CityEnergyAnalyst#1139] opened 2018-03-20 06:00 UTC
B02 in the reference case open has unrealistic/low temperatures in the column "Thsf_sup_C" in e.g. time step 71-78.

**Comment by roglen** [comment] 2018-03-20 06:01
@shanshanhsieh please have a look

**Comment by shanshanhsieh** [comment] 2018-03-21 05:57
here are the results in B02.csv, @gabriel-happle please check it out, thanks!
![image](https://user-images.githubusercontent.com/16998305/37696184-d0211b36-2d0f-11e8-90d6-44a1907e3d2b.png)

supply_systems: 
![image](https://user-images.githubusercontent.com/16998305/37696070-d4ac7642-2d0e-11e8-9986-5ee679442644.png)

technical_systems: 
![image](https://user-images.githubusercontent.com/16998305/37696060-c0a4b420-2d0e-11e8-91e5-8b9deaf30fc2.png)

**Comment by gabriel-happle** [comment] 2018-03-21 06:59
On it

**Comment by gabriel-happle** [comment] 2018-03-21 07:19
![image](https://user-images.githubusercontent.com/17002288/37697979-33fbb8ea-2d1b-11e8-9f9f-6d58b73ebc1a.png)

**Comment by gabriel-happle** [comment] 2018-03-22 02:34
@JIMENOFONSECA this is the issue we were discussing during the kanban.

**Comment by gabriel-happle** [comment] 2018-03-23 03:55
@shanshanhsieh is there any action required regarding this issue?
Or should we leave it like this for now?

**Comment by shanshanhsieh** [comment] 2018-03-23 05:12
@gabriel-happle since we are focusing on cooling cases, and this is not a bug, we can keep it as it is for now.

**Comment by gabriel-happle** [comment] 2018-03-23 06:25
closing this issue for now

**Closed by gabriel-happle** 2018-03-23 06:25 UTC
Labels: Priority 2, not a bug but...
