### ISSUE TITLE
Looped DH network simulations create MemoryErrors

### ISSUE THREAD

**Issue by martin-mosteiro** [architecture-building-systems/CityEnergyAnalyst#1753] opened 2019-01-22 09:32 UTC
We are running a simulation for a DH network with 86 connected buildings as seen below:
<img width="497" alt="screen shot 2019-01-22 at 10 16 24" src="https://user-images.githubusercontent.com/18548065/51524806-33087800-1e2f-11e9-8a4f-c03d7cf17b41.png"> <img width="497" alt="screen shot 2019-01-22 at 10 16 34" src="https://user-images.githubusercontent.com/18548065/51524809-369bff00-1e2f-11e9-9fc2-5bf20e8c27ef.png">

The student gets a memory error at the sixth diameter iteration of the simulation:
```
MemoryError
        return recv()
```

The student tried changing the simulation parameters to reduce the number of iterations at the expense of result accuracy as follows:
1- `minimum-mass-flow-iteration-limit` reduced from 30 to 10
2- Changed the simulation script to adapt tolerance as follows:
```
# adapt tolerance to reduce total amount of iterations
if iterations < 20:
    tolerance = 0.01
elif iterations < 50:
    tolerance = 0.02
elif iterations < 100:
    tolerance = 0.03
else:
    print('No convergence of looped massflows after ', iterations, ' iterations with a remaining '
```

It takes 15 iterations to set initial diameters, then the student got a warning `No convergence of initial diameter guess after 10  iterations. Continuing with main calculation.`, which leads (again) to a MemoryError on the 6th iteration.

One more change could be to reduce `diameter-iteration-limit` from 10 to 6 (again at the expense of result accuracy).

I believe @daren-thomas mentioned that this may actually be a known issue?

**Comment by shanshanhsieh** [comment] 2019-01-23 11:06
yep, i agree, the script for looped network is still quite buggy, while testing PR #1599 , I also encountered some errors during the iterations, also documenting it here for reference.

```
Individual:  [0.0, 0.0, 0.0, 0.0, 0.0, 1.0, 1.0, 0.0, 2.0, 0.0, 0.0, 0.0, 2.0, 0.0, 2.0, 2.0]
With  1  plant(s) at building(s): 
B001
With  4  disconnected building(s): 
B003
B007
B009
B010
Network has loops.
We have at least one connected building.
No first degree loop added. Trying two nodes apart.
Running thermal_network for scenario C:\Users\zshi\Documents\WTP_MIX_m_1359
Running thermal_network for network type DC
Running thermal_network for file type shp
Running thermal_network for networks []
Running thermal_network with representative week per month.
Running thermal_network with cooling loads: ['ahu', 'aru', 'scu']
Initialize network
1.22303165875 seconds process time for Network Summary

Running substation design
B002
B001
B006
B004
B005
B008
0.107932162362 seconds process time for the Substation Routine 

Calculating edge mass flows
Fundamental loops in network:  [[18, 13, 17, 3, 23, 4], [20, 12, 10, 25, 15, 7, 8], [21, 14, 9, 10, 25, 15, 7, 8, 24, 3, 23, 4, 5, 0]]
0.837405106649 seconds process time for Network Summary

......


 Initial Diameter iteration number  7

 calculating mass flows in edges... time step 0

 calculating mass flows in edges... time step 1
Stopped minimum edge mass flow iterations at:  11

 calculating mass flows in edges... time step 2

 calculating mass flows in edges... time step 3
Traceback (most recent call last):
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 867, in <module>
    main(cea.config.Configuration())
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 862, in main
    thermal_network_optimization(config, gv, locator)
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 94, in thermal_network_optimization
    sortedPop = network_cost_calculation(newMutadedGen, network_info, config)
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 158, in network_cost_calculation
    capex_total, opex_total, total_cost, cost_storage_df = objective_function(network_info)
  File "C:/Users/zshi/Documents/GitHub/CityEnergyAnalyst/cea/technologies/thermal_network/thermal_network_optimization.py", line 330, in objective_function
    thermal_network_matrix.main(network_info.config)
  File "C:\Users\zshi\Documents\GitHub\CityEnergyAnalyst\cea\technologies\thermal_network\thermal_network_matrix.py", line 3406, in main
    thermal_network_main(locator, network_type, network_name, file_type, set_diameter, config, substation_systems)
  File "C:\Users\zshi\Documents\GitHub\CityEnergyAnalyst\cea\technologies\thermal_network\thermal_network_matrix.py", line 467, in thermal_network_main
    use_multiprocessing=config.multiprocessing)
  File "C:\Users\zshi\Documents\GitHub\CityEnergyAnalyst\cea\technologies\thermal_network\thermal_network_matrix.py", line 1616, in calc_max_edge_flowrate
    diameter_guess = initial_diameter_guess(thermal_network, set_diameter, substation_systems, config)
  File "C:\Users\zshi\Documents\GitHub\CityEnergyAnalyst\cea\technologies\thermal_network\thermal_network_matrix.py", line 2120, in initial_diameter_guess
    iteration, t)
  File "C:\Users\zshi\Documents\GitHub\CityEnergyAnalyst\cea\technologies\thermal_network\thermal_network_matrix.py", line 1917, in edge_mass_flow_iteration
    thermal_network.nodes[t].append(node)
  File "C:\Users\zshi\Anaconda2\envs\cea\lib\site-packages\pandas\core\series.py", line 2156, in append
    verify_integrity=verify_integrity)
  File "C:\Users\zshi\Anaconda2\envs\cea\lib\site-packages\pandas\core\reshape\concat.py", line 225, in concat
    copy=copy, sort=sort)
  File "C:\Users\zshi\Anaconda2\envs\cea\lib\site-packages\pandas\core\reshape\concat.py", line 286, in __init__
    raise TypeError(msg)
TypeError: cannot concatenate object of type "<type 'str'>"; only pd.Series, pd.DataFrame, and pd.Panel (deprecated) objs are valid
```

**Comment by daren-thomas** [comment] 2019-01-24 09:16
- full year simulation for heating / cooling for large branched networks doesn't work.
- full year simulation of looped networks don't work either.

**Comment by JIMENOFONSECA** [comment] 2019-04-12 10:27
closing, it is a duplicate of #1855

**Closed by JIMENOFONSECA** 2019-04-12 10:27 UTC
Labels: Must have, bug
