### ISSUE TITLE
Save changes in the Dashboard

### ISSUE THREAD

**Issue by aadit879** [architecture-building-systems/CityEnergyAnalyst#3119] opened 2022-03-28 12:00 UTC
**Describe the bug**
Unable to save changes made to the CEA dashboard input editor.

**To Reproduce**
1. Go to the input editor
2. Click on 'zone'
3. Select a builidng
4. Click Edit selection. Change Building attributes.
5. Click Save.
6. See error 'Something went wrong'. Unable to save.

 -  Windows 10
 - Version of CEA  [3.26.0]

**Comment by shanshanhsieh** [comment] 2022-04-26 20:36
Hi @aadit879,

This function is working on [v3.30.0](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases)
v3.30.0 also comes with more complete error logs which will help us to better understand the errors.

closing this issue for now as we cannot reproduce it, please feel free to reopen it if the error persists.

**Closed by shanshanhsieh** 2022-04-26 20:36 UTC
Labels: bug, Interface
