### ISSUE TITLE
dashboard not starting

### ISSUE THREAD

**Issue by OmarAdnan** [architecture-building-systems/CityEnergyAnalyst#2259] opened 2019-08-17 17:42 UTC
Hi, 

I have recently installed CEA 2.20.3 (was running version 2.16 before) and after completing the installation process I tried to launch the CEA dashboard from my desktop but it just doesnt start. Is there any way to overcome this problem?

**Comment by daren-thomas** [comment] 2019-08-19 07:45
Hi @OmarAdnan how did you resolve this? Is it working for you now?

**Comment by kerembeygo** [comment] 2019-08-19 08:07
I can't find the installer for CEA 2.20.3. Installer from site is 2.14. Does PyCharm update automatically update the dashboard too?

**Comment by daren-thomas** [comment] 2019-08-19 08:23
@kerembeygo check here: https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/tag/v2.20

Not PyCharm per se - but updating from GitHub to the newest revision of the _master_ branch is the most recent version of the software.

**Comment by OmarAdnan** [comment] 2019-08-19 19:33
No it didnt work, so i downloaded 2.19 but in this version every time i try to open my project which was opening correctly in 2.16 doesnt open on 2.19, it gives : 500 internal server error

**Comment by OmarAdnan** [comment] 2019-08-19 20:33
here is the error message:

Traceback (most recent call last):
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\inputs\routes.py", line 108, in route_get_building_properties
    store['tables'][db] = json.loads(table_df.set_index('Name').to_json(orient='index'))
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 1891, in to_json
    index=index)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 58, in to_json
    index=index).write()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 93, in __init__
    self._format_axes()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 142, in _format_axes
    "'{orient}'.".format(orient=self.orient))
ValueError: DataFrame index must be unique for orient='index'.

**Comment by daren-thomas** [comment] 2019-08-20 07:50
@OmarAdnan hm... this error message doesn't help me a lot - I'm wondering. Could you explain the steps you do to "try to open my project". I'm guessing:

1. start the CEA Dashboard with the provided link
2. the browser opens with the project landing page
3. select the project folder (the parent folder of the scenario you're trying to run)
4. choose your scenario from the list of scenarios shown
5. you are sent to the input editor page

At what point does it stop working for you? When does the error come?

The error message you provided: Is that the one from the browser window? There is also an icon with the CEA logo that opens up when you start the dashboard - it's a minimized terminal with output that also might be of assistance. Could you check that for clues?

If you want, you can send us a copy of your project and we can try to replicate the error. That would help fixing the bug.

I'm re-opening this issue, as it hasn't been resolved yet.

**Comment by kerembeygo** [comment] 2019-08-20 09:37
![shallow geothermal potential 2](https://user-images.githubusercontent.com/29708612/63336049-22799b00-c347-11e9-84d6-ba1384e2cd7b.jpg)
![shallow geothermal potential](https://user-images.githubusercontent.com/29708612/63336059-27d6e580-c347-11e9-9a06-de9d83b7ac5c.jpg)

**Comment by kerembeygo** [comment] 2019-08-20 09:45
![cea sensitivity-demand-simulate](https://user-images.githubusercontent.com/29708612/63336683-3a9dea00-c348-11e9-9177-1a85b10f1009.jpg)
![cea sensitivity-demand-simulate 1](https://user-images.githubusercontent.com/29708612/63336696-3d98da80-c348-11e9-995e-7d38871d6b19.jpg)
![cea sensitivity-demand-simulate 2](https://user-images.githubusercontent.com/29708612/63336721-48ec0600-c348-11e9-9b0d-5f566a2f2cad.jpg)
![cea sensitivity-demand-simulate 3](https://user-images.githubusercontent.com/29708612/63336732-4d182380-c348-11e9-92c3-7ee79ab98077.jpg)

**Comment by OmarAdnan** [comment] 2019-08-20 09:54
@daren-thomas 
The error occurs after step 4 (of the 5 steps you mentioned above) after I select the scenario from the list of scenario and 'click' open, the error message appears.

Sorry, I don't know how to upload my scenario here, I have tried to drag and drop but I get a message that the file types are not supported here.

From the minimized terminal this is it shows:

C:\Users\Adnan\Documents\CityEnergyAnalyst>SET PATH=C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python;C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Scripts;C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Daysim;C:\Program Files\Microsoft MPI\Bin\;C:\Program Files (x86)\Intel\iCLS Client\;C:\Program Files\Intel\iCLS Client\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files\Intel\Intel(R) Management Engine Components\DAL;C:\Program Files (x86)\Intel\Intel(R) Management Engine Components\IPT;C:\Program Files\Intel\Intel(R) Management Engine Components\IPT;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files\MATLAB\MATLAB Production Server\R2015a\runtime\win64;C:\Program Files\MATLAB\MATLAB Production Server\R2015a\bin;C:\Program Files\MATLAB\MATLAB Production Server\R2015a\polyspace\bin;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\WINDOWS\System32\;C:\Program Files (x86)\NVIDIA Corporation\PhysX\Common;C:\Program Files (x86)\Microsoft SQL Server\100\Tools\Binn\;C:\Program Files (x86)\Microsoft SQL Server\100\DTS\Binn\;C:\Program Files\NVIDIA Corporation\NVIDIA NvDLISR;C:\Users\Adnan\AppData\Local\Microsoft\WindowsApps;

C:\Users\Adnan\Documents\CityEnergyAnalyst>SET PYTHONHOME=C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python

C:\Users\Adnan\Documents\CityEnergyAnalyst>SET PYTHONHOME=C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python

C:\Users\Adnan\Documents\CityEnergyAnalyst>SET GDAL_DATA=C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share\gdal

C:\Users\Adnan\Documents\CityEnergyAnalyst>SET PROJ_LIB=C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share

C:\Users\Adnan\Documents\CityEnergyAnalyst>SET RAYPATH=C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Daysim

C:\Users\Adnan\Documents\CityEnergyAnalyst>"C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\python.exe" -m cea.interfaces.cli.cli dashboard
City Energy Analyst version 2.20.3
Running `cea dashboard` with the following parameters:
- general:debug = False
  (default: False)
cea.api: loading cea_script: <cea compile>
cea.api: loading cea_script: <cea excel-to-shapefile>
cea.api: loading cea_script: <cea install-arcgis>
cea.api: loading cea_script: <cea workflow>
cea.api: loading cea_script: <cea test>
cea.api: loading cea_script: <cea list-demand-graphs-fields>
cea.api: loading cea_script: <cea dashboard>
cea.api: loading cea_script: <cea install-grasshopper>
cea.api: loading cea_script: <cea graphviz>
cea.api: loading cea_script: <cea extract-reference-case>
cea.api: loading cea_script: <cea dbf-to-excel-to-dbf>
cea.api: loading cea_script: <cea trace-inputlocator>
cea.api: loading cea_script: <cea shapefile-to-excel>
cea.api: loading cea_script: <cea html>
cea.api: loading cea_script: <cea demand>
cea.api: loading cea_script: <cea update-naming>
cea.api: loading cea_script: <cea photovoltaic>
cea.api: loading cea_script: <cea shallow-geothermal-potential>
cea.api: loading cea_script: <cea glossary>
cea.api: loading cea_script: <cea optimization>
C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\deap\tools\_hypervolume\pyhv.py:33: ImportWarning:

Falling back to the python version of hypervolume module. Expect this to be very slow.

cea.api: loading cea_script: <cea sewage-potential>
cea.api: loading cea_script: <cea rename-building>
cea.api: loading cea_script: <cea network-layout>
cea.api: loading cea_script: <cea photovoltaic-thermal>
cea.api: loading cea_script: <cea water-body-potential>
cea.api: loading cea_script: <cea benchmark-graphs>
cea.api: loading cea_script: <cea emissions>
cea.api: loading cea_script: <cea thermal-network-optimization>
cea.api: loading cea_script: <cea sensitivity-demand-samples>
cea.api: loading cea_script: <cea multi-criteria-analysis>
cea.api: loading cea_script: <cea radiation-daysim>
cea.api: loading cea_script: <cea thermal-network>
cea.api: loading cea_script: <cea sensitivity-demand-simulate>
cea.api: loading cea_script: <cea decentralized>
cea.api: loading cea_script: <cea district-helper>
cea.api: loading cea_script: <cea operation-costs>
cea.api: loading cea_script: <cea zone-helper>
cea.api: loading cea_script: <cea sensitivity-demand-analyze>
cea.api: loading cea_script: <cea data-helper>
cea.api: loading cea_script: <cea terrain-helper>
cea.api: loading cea_script: <cea streets-helper>
cea.api: loading cea_script: <cea solar-collector>
cea.api: loading cea_script: <cea plots>
 * Serving Flask app "cea.interfaces.dashboard.dashboard" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
INFO:werkzeug: * Running on http://localhost:5050/ (Press CTRL+C to quit)
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:27] "GET / HTTP/1.1" 302 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:28] "GET /landing/welcome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:28] "GET /static/vendors/jquery-ui/jquery-ui.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/bootstrap/dist/css/bootstrap.min.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/font-awesome/css/font-awesome.min.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/nprogress/nprogress.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/bootstrap-daterangepicker/daterangepicker.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/iCheck/skins/flat/green.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/bootstrap-progressbar/css/bootstrap-progressbar-3.3.4.min.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/jqvmap/dist/jqvmap.min.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/switchery/dist/switchery.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /landing/static/landing.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/build/css/custom.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/jquery/dist/jquery.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:29] "GET /static/vendors/jquery-ui/jquery-ui.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/bootstrap/dist/js/bootstrap.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/font-awesome/fonts/fontawesome-webfont.woff2?v=4.6.3 HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/images/cea-logo.png HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/fastclick/lib/fastclick.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/nprogress/nprogress.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/iCheck/icheck.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/moment/min/moment.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/bootstrap-daterangepicker/daterangepicker.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/bootstrap-wysiwyg/js/bootstrap-wysiwyg.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/jquery.hotkeys/jquery.hotkeys.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/google-code-prettify/src/prettify.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:30] "GET /static/vendors/jquery.tagsinput/src/jquery.tagsinput.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:31] "GET /static/vendors/switchery/dist/switchery.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:31] "GET /static/vendors/select2/dist/js/select2.full.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:31] "GET /static/vendors/autosize/dist/autosize.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:31] "GET /static/vendors/devbridge-autocomplete/dist/jquery.autocomplete.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:31] "GET /static/build/js/glossary_search.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:31] "GET /static/vendors/starrr/dist/starrr.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:31] "GET /landing/welcome HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:56] "GET /landing/open-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:56] "GET /tools/static/tools.css HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:57] "GET /static/vendors/parsleyjs/dist/parsley.min.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:57] "GET /tools/static/tools.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:33:57] "GET /landing/open-project HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:40:38] "POST /landing/open-project/save HTTP/1.1" 302 -
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:GDAL_DATA: C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share\gdal
DEBUG:Fiona:PROJ_LIB: C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share
DEBUG:Fiona:GDAL_DATA: C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share\gdal
DEBUG:Fiona:PROJ_LIB: C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
C:\Users\Adnan\Documents\IST Files\Thesis\CityEnergyAnalysis tutorials\Thesis\.cache\Scenario.png
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:40:39] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:40:39] "GET /static/build/js/custom.js HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:40:40] "GET /static/vendors/bootstrap/dist/fonts/glyphicons-halflings-regular.woff2 HTTP/1.1" 304 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:40:40] "GET /landing/get-image/Scenario HTTP/1.1" 200 -
DEBUG:fiona:Creating a not-responsible GDALEnv in drivers()
DEBUG:Fiona:GDAL_DATA: C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share\gdal
DEBUG:Fiona:PROJ_LIB: C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share
DEBUG:Fiona:GDAL_DATA: C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share\gdal
DEBUG:Fiona:PROJ_LIB: C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\Library\share
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Got coordinate system
DEBUG:Fiona:Index: 0
DEBUG:fiona.collection:Flushed buffer
DEBUG:fiona.collection:Stopped session
C:\Users\Adnan\Documents\IST Files\Thesis\CityEnergyAnalysis tutorials\Thesis\.cache\Scenario.png
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:40:40] "GET /landing/project-overview HTTP/1.1" 200 -
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:44:07] "GET /landing/open-project/Scenario HTTP/1.1" 302 -
ERROR:flask.app:Exception on /inputs/building-properties [GET]
Traceback (most recent call last):
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\inputs\routes.py", line 108, in route_get_building_properties
    store['tables'][db] = json.loads(table_df.set_index('Name').to_json(orient='index'))
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 1891, in to_json
    index=index)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 58, in to_json
    index=index).write()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 93, in __init__
    self._format_axes()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 142, in _format_axes
    "'{orient}'.".format(orient=self.orient))
ValueError: DataFrame index must be unique for orient='index'.
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:44:07] "GET /inputs/building-properties HTTP/1.1" 500 -
ERROR:flask.app:Exception on /inputs/building-properties [GET]
Traceback (most recent call last):
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\cea\interfaces\dashboard\inputs\routes.py", line 108, in route_get_building_properties
    store['tables'][db] = json.loads(table_df.set_index('Name').to_json(orient='index'))
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\core\generic.py", line 1891, in to_json
    index=index)
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 58, in to_json
    index=index).write()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 93, in __init__
    self._format_axes()
  File "C:\Users\Adnan\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\pandas\io\json\json.py", line 142, in _format_axes
    "'{orient}'.".format(orient=self.orient))
ValueError: DataFrame index must be unique for orient='index'.
INFO:werkzeug:127.0.0.1 - - [20/Aug/2019 10:44:08] "GET /inputs/building-properties HTTP/1.1" 500 -

**Comment by kerembeygo** [comment] 2019-08-20 09:56
![network-layout](https://user-images.githubusercontent.com/29708612/63337357-87ce8b80-c349-11e9-8bc4-6120321593b2.jpg)
![network-layout 1](https://user-images.githubusercontent.com/29708612/63337368-8bfaa900-c349-11e9-86ff-90d6ae859722.jpg)
![network-layout 2](https://user-images.githubusercontent.com/29708612/63337367-8b621280-c349-11e9-94ea-2fd0762cfa6c.jpg)
![network-layout 3](https://user-images.githubusercontent.com/29708612/63337370-8dc46c80-c349-11e9-8f61-4e2adc333db1.jpg)
UnboundLocalError: local variable 'field' referenced before assignment

**Comment by kerembeygo** [comment] 2019-08-20 10:04
![water-body-potential](https://user-images.githubusercontent.com/29708612/63338088-d4669680-c34a-11e9-8e18-72bf0ffb443b.jpg)
![Central supply system](https://user-images.githubusercontent.com/29708612/63338093-d6c8f080-c34a-11e9-9b94-96f51a39028c.jpg)
![Central supply system 1](https://user-images.githubusercontent.com/29708612/63338098-d892b400-c34a-11e9-9da2-4099690be4ab.jpg)
Missing geothermal potential of the scenario. Consider running lake potential script first.

**Comment by daren-thomas** [comment] 2019-08-21 08:57
@kerembeygo your errors, while very helpful, seem unrelated to the current issue. Would you mind in the future creating separate issues for these? Each of the screenshots you posted is it's own issue / potential bug in the code.

I'll move them to separate issues and remove them from this issue as they're distracting from the issue at hand. (see #2268, #2269, #2270, #2271)

**Comment by daren-thomas** [comment] 2019-08-21 09:24
@OmarAdnan with the scenario you supplied, I'm able to reproduce the error in the master branch. May I ask: How did you create this scenario?

I have checked and traced the problem down to the index in `restrictions.dbf` not being unique: You specify the same buildings multiple times. A rough check suggests they're doubled...

**Comment by daren-thomas** [comment] 2019-08-21 09:27
The zone file has 370 buildings, but the unique set of `Name` values is 185. The other `.dbf` files show much more than 370 buildings, (1480, 8*185) - I'm wondering if this happened by manually editing these files (in Excel?) or if our software did this. Do you have any clues?

**Comment by OmarAdnan** [comment] 2019-08-21 10:31
@daren-thomas 
These shapefiles which are of Lisbon was provided to me by my professor, which I have edited using QGIS and reduced to a small area in the city to do my first analysis of the solar radiation potential using daysim in CEA. The zone .dbf file I have edited to create the 5 columns that CEA needs to read my shapefile correctly, which are the Name, height_ag, height_bg, floor_ag and floor_bg as the initial version of the data had columns that weren't needed by CEA.

I don't know if this number of building change is caused by QGIS or CEA, is there any way to fix this? maybe by editing the dbf file again in QGIS, will that fix the issue? or does it seem like I have to recreate the scenario again from the original shapefiles?

**Comment by OmarAdnan** [comment] 2019-08-21 10:37
Furthermore, this scenario could easily be opened on CEA 2.16, but on that version when i try to run daysim, it would either keep running for every or at times gave me an error. After a little digging on github i learned that i was mainly due to the addition of University and Industrial column in the occupancy dbf file. Hence, I downloaded the latest version of CEA hoping it will work here correctly.
I believe the in order to run the daysim the important inputs are the building height and shape, along with the terrain and weather data, all of which I have provided, the rest of the files inside the scenario i have generated using the data helper.

**Comment by daren-thomas** [comment] 2019-08-21 10:47
Mainly, the problem seems to be that some rows are duplicates - the `Name` column should be unique. If you can edit your data to be that way, that would be the easiest.

**Comment by OmarAdnan** [comment] 2019-08-21 10:52
Alright, I shall try it out and see if it helps but just a small question, will be ok to just change the name of buildings in Name column that are repeated? or there are some other things that need to be done

**Comment by daren-thomas** [comment] 2019-08-22 06:25
@OmarAdnan I'm not sure: It seems the various files don't agree on the total number of buildings in your project. I'm guessing, at some point, the datasets got duplicated. If I were you, I'd compare to the originals you got from your professor.

If you're handy with python, using a `jupyter notebook` could be a handy place for cleaning up the data. You can use the `cea.utilities.dbf.dbf_to_dataframe(path_to_dbf)` function to get a pandas Dataframe of a dbf file... (https://city-energy-analyst.readthedocs.io/en/latest/modules/cea.utilities.html#cea.utilities.dbf.dbf_to_dataframe)

**Comment by daren-thomas** [comment] 2019-08-22 07:50
I'm closing this issue as the problem seems to have been found and is related to the input data, not the dashboard itself.

**Closed by daren-thomas** 2019-08-22 07:50 UTC
