### ISSUE TITLE
Dashboard not starting

### ISSUE THREAD

**Issue by schneidernt** [architecture-building-systems/CityEnergyAnalyst#3443] opened 2024-01-04 07:10 UTC
**Describe the bug**
Hi, after I install CEA via the express installation and try to start the dashboard I receive the following error

**To Reproduce**
1. Installing CAE
2. double click on the dashboard

**Expected behaviour**

**Screenshots**
<img width="419" alt="image" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/155615412/543c7acb-4c9f-45d2-b6f2-a911594b40af">
<img width="413" alt="image" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/155615412/125b18b3-aae9-42e8-8f33-4593e9eb0c96">
<img width="415" alt="image" src="https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/155615412/2d8d3b31-670b-4de6-88ef-7e5bd9d1dbf1">

**Hardware (please complete the following information):**
 - Windows 11
 - Version of CEA you are using [e.g. v. 2.31.1]

**Comment by ShiZhongming** [comment] 2024-01-08 14:02
@reyery 
Any idea about this? :)

**Comment by BiaPri** [comment] 2024-01-18 10:18
Good morning,
Similar error on my side,

![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/36563911/d92f3331-c501-472c-a387-cbe3163eeca5)

Besides this tool is really great!

B.

**Comment by reyery** [comment] 2024-01-19 12:18
Hi @schneidernt and @BiaPri, thank you for reporting these issues. 

Both issues seem to have something to do with the python dependencies of CEA. We have recently released a new version of CEA that should solve this issue. Try uninstalling and reinstalling the new version, and let me know if that works for you. You can download the new installation [here](https://github.com/architecture-building-systems/CityEnergyAnalyst/releases/download/v3.35.1/Setup_CityEnergyAnalyst_3.35.1.exe).

**Comment by BiaPri** [comment] 2024-01-24 13:45
Good afternoon,

The problem is persisting, someone can help?
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/36563911/248071c2-197c-46cd-9959-30714e3b8fd7)

Thank you for the support,

B.

**Comment by reyery** [comment] 2024-01-24 13:49
@BiaPri could you open the CEA Console and run the following command
```
conda list
```

**Comment by BiaPri** [comment] 2024-01-24 15:17
Should install anaconda?
![image](https://github.com/architecture-building-systems/CityEnergyAnalyst/assets/36563911/3f7e401f-0cb7-4764-b604-c7b616d5f87e)

**Comment by reyery** [comment] 2024-01-25 10:57
Not necessarily. Based on the previous error, the python dependencies `numpy`and `numba` are the ones that are causing the issue. This was fixed in the new version of CEA, so I am not too sure why they are still happening for you.

Let's try manually installing both
```
python -m pip install numba==0.57 numpy==1.24.4
```

Let me know if that works for you.

**Comment by BiaPri** [comment] 2024-01-25 20:44
Strange indeed,
all set, thank you for the support @reyery !

**Comment by reyery** [comment] 2024-01-26 08:46
I will close this issue for now. If there are any more issue, we can continue on a new one.

**Closed by reyery** 2024-01-26 08:46 UTC
Labels: bug
