### ISSUE TITLE
thermal storage for solar collectors at buildings

### ISSUE THREAD

**Issue by shanshanhsieh** [architecture-building-systems/CityEnergyAnalyst#1513] opened 2018-06-18 10:52 UTC
If using evacuated tubes + absorption chillers, there are with excess cooling production.
In this cases, there should be a cold water tank or a hot water tank to store the excess production.

**Comment by JIMENOFONSECA** [comment] 2019-04-12 10:07
@shanshanhsieh do you think we can/should use this feature for the executive course?

**Comment by shanshanhsieh** [comment] 2019-04-18 02:53
Solar thermal + cooling is not more competitive than PV + vapor compression chillers at building levels
(in terms of price, efficiency, space, maintenance...)
in my opinion, it is more worth exploring in industrial sites that requires heating, and can use absorption chillers to leverage the excess heat production from solar thermal collectors...

**Comment by JIMENOFONSECA** [comment] 2019-04-18 06:22
Alright so it is out and we leave it for future work.

**Comment by daren-thomas** [comment] 2019-04-18 09:01
Reopening as the issue is not closed, but rather deferred. Maybe we need a label for this kind of issue? ("closed" means we won't be revisiting this ever again...)

**Comment by JIMENOFONSECA** [comment] 2019-11-01 01:34
1.5 years in here, we will not have it anytime soon. Closing it.

**Closed by JIMENOFONSECA** 2019-11-01 01:34 UTC
Labels: Won't have, enhancement, known issue
