### ISSUE TITLE
Weather helper not running

### ISSUE THREAD

**Issue by lguilhermers** [architecture-building-systems/CityEnergyAnalyst#2389] opened 2019-10-15 09:12 UTC
When trying to run weather helper, I get directed to a new page with the following message, before I can even select a weather:

Traceback (most recent call last): File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 2292, in wsgi_app response = self.full_dispatch_request() File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1815, in full_dispatch_request rv = self.handle_user_exception(e) File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router return original_handler(e) File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask_restplus\api.py", line 584, in error_router return original_handler(e) File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1718, in handle_user_exception reraise(exc_type, exc_value, tb) File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1813, in full_dispatch_request rv = self.dispatch_request() File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\app.py", line 1799, in dispatch_request return self.view_functions[rule.endpoint](**req.view_args) File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\tools\routes.py", line 154, in route_tool weather_dict=weather_dict, last_updated=dir_last_updated()) File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\templating.py", line 135, in render_template context, ctx.app) File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\flask\templating.py", line 117, in _render rv = template.render(context) File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\jinja2\environment.py", line 1008, in render return self.environment.handle_exception(exc_info, True) File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\jinja2\environment.py", line 780, in handle_exception reraise(exc_type, exc_value, tb) File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\tools\templates\tool.html", line 5, in top-level template code {% import 'input_macros.html' as input_macros %} File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\base\templates\base_site.html", line 42, in top-level template code {% block body %} File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\base\templates\base_site.html", line 58, in block "body" {% block content %} File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\tools\templates\tool.html", line 75, in block "content" {{ input_macros.input(parameter, weather_dict) }} File "C:\Users\luis.santos\Documents\CityEnergyAnalyst\Dependencies\Python\lib\site-packages\jinja2\runtime.py", line 579, in _invoke rv = self._func(*arguments) File "c:\users\luis.santos\documents\cityenergyanalyst\cityenergyanalyst\cea\interfaces\dashboard\tools\templates\input_macros.html", line 87, in template

**Comment by JIMENOFONSECA** [comment] 2019-10-15 09:55
@reyery any ideas? I am not able to reproduce the error. @lguilhermers are you in master right? This might be a duplicate of #2381

**Closed** 2019-10-16 02:57 UTC
