### ISSUE TITLE
Update the reference-case-open to test all the technical systems

### ISSUE THREAD

**Issue by daren-thomas** [architecture-building-systems/CityEnergyAnalyst#943] opened 2017-12-18 14:24 UTC
Currently, this is the list of systems being tested:

```
  | Name | type_cs | type_ctrl | type_dhw | type_hs | type_vent
-- | -- | -- | -- | -- | -- | --
0 | B01 | T3 | T1 | T1 | T1 | T1
1 | B02 | T3 | T1 | T1 | T1 | T1
2 | B03 | T3 | T2 | T1 | T2 | T1
3 | B04 | T3 | T2 | T1 | T2 | T1
4 | B05 | T3 | T2 | T1 | T2 | T1
5 | B06 | T0 | T1 | T0 | T0 | T1
6 | B07 | T3 | T2 | T1 | T2 | T1
7 | B08 | T3 | T2 | T1 | T2 | T1
8 | B09 | T3 | T2 | T1 | T2 | T1
```

There should be more variation here - we should be testing as many code paths as possible.

**Comment by JIMENOFONSECA** [comment] 2018-02-26 07:00
closing as this is a duplicate of #1061

**Closed by JIMENOFONSECA** 2018-02-26 07:00 UTC
Labels: Priority 1, duplicate, enhancement
