### ISSUE TITLE
Bug in ARU air-conditioning model calculations

### ISSUE THREAD

**Issue by gabriel-happle** [architecture-building-systems/CityEnergyAnalyst#1588] opened 2018-07-19 06:57 UTC
@martin-mosteiro reported strange behavior of the air conditioning model for the case when there is dehumidification and the interior air temperature is below the cooling supply temperature. this happens in spring in a very poorly insulated building outside the heating season.

**Comment by gabriel-happle** [comment] 2018-07-19 07:17
There is a bug in the script where the maximum possible dehumidification demand can turn positive (should be negative) in cases with very low zone internal moisture content (below the off coil humidity content at the ARU). This can only happen in temperate climates and was probably overlooked during testing for the Singapore case.

**Comment by martin-mosteiro** [comment] 2018-07-19 15:50
The moisture removed by the ARU has a different sign in different parts of the code. This results in the building sometimes having a positive value for `g_dhu_aru` and sometimes a negative one in the final results.

@gabriel-happle I'm adding a fix for this, but since I am not sure if this is consistent with your assumptions, I'm going to need you to check it!

**Comment by martin-mosteiro** [comment] 2018-07-25 11:54
This is technically a different issue but I'm adding it to this one because it is the final fix that is needed for the Zurich case study to run. Currently, the demand script gives the following error for some buildings:
```
Traceback (most recent call last):
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 211, in <module>
    main(cea.config.Configuration())
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 195, in main
    demand_calculation(locator=locator, gv=cea.globalvar.GlobalVariables(), config=config)
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 110, in demand_calculation
    format_output, region)
  File "C:/Users/User/Documents/GitHub/CityEnergyAnalyst/cea/demand/demand_main.py", line 154, in calc_demand_singleprocessing
    format_output, region)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 125, in calc_thermal_loads
    tsd = calc_Qcs_sys(bpr, tsd) # final : including fuels and renewables
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\demand\thermal_loads.py", line 203, in calc_Qcs_sys
    (tsd['Tcs_sys_re_aru'] + 273), t_source)
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2734, in __call__
    return self._vectorize_call(func=func, args=vargs)
  File "C:\Users\User\Miniconda2\envs\cea\lib\site-packages\numpy\lib\function_base.py", line 2810, in _vectorize_call
    outputs = ufunc(*inputs)
  File "C:\Users\User\Documents\GitHub\CityEnergyAnalyst\cea\technologies\heatpumps.py", line 57, in HP_air_air
    COP = HP_ETA_EX_COOL * tevap_K / (tcond_K - tevap_K)
ZeroDivisionError: float division by zero

Process finished with exit code 1
```
This error is due to the evaporator temperature (7.5°C) being equal to the condenser temperature (which is equal to the outdoor temperature). i.e., there's cooling in the building while the temperature outside is 7.5°C. This occurs currently for some buildings due to unrealistically high electrical demands, caused by a separate issue (#1374). However, I think it makes sense to have a solution to the above issue in any case.

Here's the part of the code being affected:
```
        # calculate COP
        COP = HP_ETA_EX_COOL * tevap_K / (tcond_K - tevap_K)
        qcolddot_W = mdot_cp_WC * (t_re_K - t_sup_K)

        # in order to work in the limits of the equation
        if COP > 8.5:  # maximum achieved by 3for2 21.05.18
            COP = 8.5
        elif COP < 1.0:
            COP = 2.7  # COP of typical air-to-air unit
```
If `tcond_K` is equal to `tevap_K`, then the COP would tend to infinity; since infinity is greater than 8.5 and the maximum considered is 8.5, the issue could be solved as follows:
```
        # calculate COP
        if np.isclose(tcond_K, tevap_K):
                print('condenser temperature is equal to evaporator temperatur, COP set to the maximum')
                COP = 8.5
        else:
                COP = HP_ETA_EX_COOL * tevap_K / (tcond_K - tevap_K)


        # in order to work in the limits of the equation
        if COP > 8.5:  # maximum achieved by 3for2 21.05.18
            COP = 8.5
        elif COP < 1.0:
            COP = 2.7  # COP of typical air-to-air unit

        qcolddot_W = mdot_cp_WC * (t_re_K - t_sup_K)
```
(The printed comment was added at @shanshanhsieh's request)
@gabriel-happle Does this make sense to you?

**Comment by martin-mosteiro** [comment] 2018-07-25 12:17
Even better:
```
        # calculate COP
        if np.isclose(tcond_K, tevap_K):
                print('condenser temperature is equal to evaporator temperature, COP set to the maximum')
                COP = HP_COP_MAX
        else:
                COP = HP_ETA_EX_COOL * tevap_K / (tcond_K - tevap_K)


        # in order to work in the limits of the equation
        if COP > HP_COP_MAX:
            COP = HP_COP_MAX
        elif COP < 1.0:
            COP = HP_COP_MIN

        qcolddot_W = mdot_cp_WC * (t_re_K - t_sup_K)
```
where
```
HP_COP_MAX = 8.5:  # maximum achieved by 3for2 21.05.18
HP_COP_MIN = 2.7  # COP of typical air-to-air unit
```
are defined in the appropriate `constants.py` file.

**Comment by martin-mosteiro** [comment] 2018-07-25 13:16
After making both the ARU and COP changes, the Zurich case study runs correctly.

**Comment by gabriel-happle** [comment] 2018-07-26 02:35
Nice! Let's create a PR then.

**Closed** 2018-08-23 07:49 UTC
Labels: Priority 1, bug
